### PR TITLE
Show hint how to turn on hints again immediately after deactivation

### LINKED ISSUE #1057: Hints for `machinery config hint` is broken
Hints for `machinery config hint` is broken. 

See:
```
# machinery config hints on
hints = true
# machinery config hints off
hints = false
# machinery config hints off
hints = false
Hints can be switched on again by '/usr/bin/machinery config hints=on'.
```
It should show the hint if and only if the value of hints is toggled.

### LINKED ISSUE #1058: machinery config --help should mention `KEY=VALUE` syntax
`machinery config --help` prints:
```
NAME
    config - Show or change machinery's configuration

SYNOPSIS
    machinery [global options] config [KEY] [VALUE]

DESCRIPTION
    Show or change machinery's configuration.

    The value of a key is shown when no value argument is passed. If neither
    the key argument nor the value argument are specified a list of all keys and
    their values are shown. 
```

It should also mention that the syntax `KEY=VALUE` is also valid.

### PR DESCRIPTION
**Pull request by keberle94**
Fixes #1057

### CODE REVIEW

File: lib/cli.rb [hunk 1]
```diff
@@ -742,7 +742,7 @@ def self.parse_scopes(scope_string)
       task = ConfigTask.new
       task.config(key, value)
 
-      if key == "hints" && !@config.hints
+      if key == "hints" && value == "false"
```
Comment (tgoettlicher) [inline lib/cli.rb]: Does this also work with `hints=off` instead of `hints=false`?

**Comment by keberle94** [comment]
No you are right. I forgot about that way. Now it should.

**Comment by tgoettlicher** [comment]
lgtm
