### PR TITLE
Optimize assert_scope to be copyable by the user

### LINKED ISSUE #2002: Analyze command recommends incorrect scope name for config files
```
 $ bin/machinery analyze grub2
The system description misses the following scopes : os, repositories, config_files.
 $ bin/machinery inspect e11.suse.de -n grub2 -s os,repositories,config_files                                                                                                                 
The following scope is not valid: 'config_files'. Scope names must start with a letter and contain only lowercase letters and digits separated by dashes ('-').
```

### PR DESCRIPTION
**Pull request by thardeck**
Fixes #2002

### CODE REVIEW

File: spec/unit/system_description_spec.rb [hunk 1]
```diff
@@ -197,22 +197,29 @@ class SystemDescriptionFooConfig < Machinery::Object; end
...
           missing.each do |element|
             description.send("#{element}=", nil)
           end
-          description.assert_scopes("repositories", "packages")
+          description.assert_scopes("repositories", "packages", "config_files")
         }.to raise_error(
            Machinery::Errors::SystemDescriptionError,
-           /: #{missing.join(", ")}\./)
+           /: #{missing.map { |scope|
+             Machinery::Ui.internal_scope_list_to_string(scope)
```
Comment (mauromorales) [inline spec/unit/system_description_spec.rb]: I'd prefer to have the specif text checked here

File: spec/unit/system_description_spec.rb [hunk 2]
```diff
@@ -197,22 +197,29 @@ class SystemDescriptionFooConfig < Machinery::Object; end
...
+    }
+
     it "checks the system description for completeness" do
-      full_description = create_test_description(name: @name, json: @description)
       [
         ["repositories"],
         ["packages"],
-        ["repositories", "packages"]
+        ["repositories", "packages", "config_files"]
       ].each do |missing|
```
Comment (mauromorales) [inline spec/unit/system_description_spec.rb]: Do we really need to test each case? we could just test the case when the required scopes are there and when they are not

**Comment by mauromorales** [comment]
lgtm
