### PR TITLE
Fix `machinery remove` return code

### LINKED ISSUE #553: machinery remove pretends success when it couldn't delete the system description
machinery remove exits with with return value `0`, although the operation failed. It used to exit with code `1`. 

```
# machinery remove does_not_exist
System description "does_not_exist" does not exist.
# echo $?
0
```

### PR DESCRIPTION
**Pull request by Werni**
Machinery should exit with return code != 0 when a description does
not exists.

Fixes #553

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged e169d270d97bed5f89f8fcc72b189e63ded83d32 into b82d71038ea6d59833d883e4240e71bda4e2c30b )

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged ce6c0acf52455361367905035af26a10a252f15a into b82d71038ea6d59833d883e4240e71bda4e2c30b )

File: spec/unit/remove_task_spec.rb [hunk 1]
```diff
@@ -47,12 +47,10 @@
...
-    it "show a warning when SystemDescription does not exist" do
-      expect(Machinery::Ui).to receive(:warn).with(
-        "System description \"foo_bar_does_not_exist\" does not exist."
-      )
-
-      remove_task.remove(store, "foo_bar_does_not_exist")
+    it "throws an error when SystemDescription does not exist" do
+      expect {
+        remove_task.remove(store, "foo_bar_does_not_exist")
+      }.to raise_error(Machinery::Errors::SystemDescriptionNotFound)
```
Comment (thardeck) [inline spec/unit/remove_task_spec.rb]: I would remove two descriptions of which is one is missing and make sure that the other one is removed besides showin the error to adhere to the acceptance criteria.

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
( Success: Merged 60e17c7229ab15eac1e52865d794dc696dbbef04 into b82d71038ea6d59833d883e4240e71bda4e2c30b )

**Comment by thardeck** [comment]
lgtm
