### PR TITLE
Fix wrong alert when a scope is missing from both descriptions

### LINKED ISSUE #1508: There is an empty alert shown in the HTML comparison
See screenshot:

rendered1

It's comparing two descriptions which each hav a package, repositories, and an extracted unmanaged files scope.

### PR DESCRIPTION
**Pull request by aduffeck**
Fixes #1508

### CODE REVIEW

File: lib/server.rb [hunk 1]
```diff
@@ -231,7 +231,7 @@ def diff_to_object(diff)
     Inspector.all_scopes.each do |scope|
       if @description_a[scope] && @description_b[scope]
         @diff[scope] = Comparison.compare_scope(@description_a, @description_b, scope)
-      else
+      elsif @description_a[scope] || @description_b[scope]
         @meta[:uninspected] ||= Hash.new
 
         if !@description_a[scope] && @description_b[scope]
```
Comment (thardeck) [inline lib/server.rb]: Couldn't the later be now removed for both?

**Comment by thardeck** [comment]
lgtm
