### PR TITLE
Check for iso image

### LINKED ISSUE #1032: Machinery build fails when repository is an iso file
Please see:
https://github.com/SUSE/machinery/issues/617
https://github.com/SUSE/machinery/pull/625
https://github.com/SUSE/machinery/pull/624

```
peon@dhcp110:~> dev/machinery/bin/machinery build -i ./build_img ceph_admin_node -d -s
DHCP in built image will be enabled for the first device
peon's password:
Jun-24 15:18:00 <1> : Setting log file to: /tmp/machinery-image20150624-5413-k2qelu/kiwi-terminal-output.log
+ export PBL_SKIP_BOOT_TEST=1
+ PBL_SKIP_BOOT_TEST=1
+ trap clean INT TERM
+ export ZYPP_MODALIAS_SYSFS=/tmp
+ ZYPP_MODALIAS_SYSFS=/tmp
+ export YAST_IS_RUNNING=true
+ YAST_IS_RUNNING=true
+ export ZYPP_CONF=/tmp/machinery-image20150624-5413-k2qelu/build/image-root//var/cache/kiwi/zypper/zypp.conf.5428
+ ZYPP_CONF=/tmp/machinery-image20150624-5413-k2qelu/build/image-root//var/cache/kiwi/zypper/zypp.conf.5428
+ export ZYPP_LOCKFILE_ROOT=/tmp/machinery-image20150624-5413-k2qelu/build/image-root
+ ZYPP_LOCKFILE_ROOT=/tmp/machinery-image20150624-5413-k2qelu/build/image-root
+ mkdir -p /tmp/machinery-image20150624-5413-k2qelu/build/image-root/etc/zypp
+ SPID=5602
+ wait 5602
+ /usr/bin/zypper --non-interactive --pkg-cache-dir /var/cache/kiwi/packages --reposd-dir /tmp/machinery-image20150624-5413-k2qelu/build/image-root//var/cache/kiwi/zypper/repos --solv-cache-dir /tmp/machinery-image20150624-5413-k2qelu/build/image-root//var/cache/kiwi/zypper/solv --cache-dir /tmp/machinery-image20150624-5413-k2qelu/build/image-root//var/cache/kiwi/zypper --config /var/cache/kiwi/zypper/zypper.conf.5428 --no-gpg-checks --root /tmp/machinery-image20150624-5413-k2qelu/build/image-root install --auto-agree-with-licenses --no-recommends FirmwareUpdateKit Mesa Mesa-32bit Mesa-demo-x Mesa-libEGL1 Mesa-libEGL1-32bit Mesa-libGL1 Mesa-libGL1-32bit Mesa-libGLESv2-2 Mesa-libglapi0 Mesa-libglapi0-32bit MozillaFirefox MozillaFirefox-branding-SLE MozillaFirefox-translations OpenIPMI PackageKit PackageKit-backend-zypp PackageKit-branding-SLE PackageKit-lang SUSEConnect SuSEfirewall2 aaa_base aaa_base-extras accountsservice accountsservice-lang acl adaptec-firmware adjtimex alsa alsa-plugins alsa-plugins-pulse alsa-utils apache2 apache2-mod_wsgi apache2-prefork apache2-utils apparmor-docs apparmor-parser apparmor-profiles apparmor-utils appres at at-spi2-atk-common at-spi2-atk-gtk2 at-spi2-core atmel-firmware attr audit augeas-lenses autoconf autofs automake autoyast2 autoyast2-installation bash bash-completion bash-doc bc bind-libs bind-libs-32bit bind-utils binutils bitmap bitstream-vera-fonts blktrace bluez boost-license1_54_0 branding-SLE brasero brasero-lang brltty btrfsmaintenance btrfsprogs bzip2 ca-certificates ca-certificates-mozilla calamari-clients calamari-server cantarell-fonts caribou-common cdrdao cdrkit-cdrtools-compat ceph ceph-common ceph-deploy checkmedia cifs-utils clutter-gtk-lang clutter-lang cogl-lang colord-gtk-lang command-not-found convmv coreutils coreutils-lang cpio cpio-lang cpp cpp48 cpupower cracklib cracklib-dict-full crash crash-kmp-default cron cronie cryptconfig cryptconfig-32bit cryptsetup cups cups-client cups-filters cups-filters-cups-browsed cups-filters-foomatic-rip cups-filters-ghostscript cups-libs cups-libs-32bit cups-pk-helper cups-pk-helper-lang curl cyrus-sasl cyrus-sasl-32bit cyrus-sasl-digestmd5 cyrus-sasl-gssapi cyrus-sasl-gssapi-32bit cyrus-sasl-plain cyrus-sasl-plain-32bit cyrus-sasl-saslauthd db48-utils dbus-1 dbus-1-glib dbus-1-glib-32bit dbus-1-python dbus-1-python3 dbus-1-x11 dconf dconf-lang dejavu-fonts delayacct-utils deltarpm desktop-data-SLE desktop-file-utils desktop-translations device-mapper device-mapper-32bit dhcp dhcp-client dialog diffutils dirmngr dmidecode dmraid dmz-icon-theme-cursors docbook_4 dos2unix dosfstools dracut e2fsprogs ed editres efibootmgr efont-unicode-bitmap-fonts elfutils eog eog-lang espeak ethtool evince evince-lang expat expect fastjar fd0ssh fdupes file file-magic file-roller file-roller-lang filesystem fillup findutils finger fipscheck fontconfig fontconfig-32bit fonts-config fonttosfnt fping freetype fribidi fribidi-32bit ft2demos fuse gamin-server gawk gconf-editor gconf-editor-lang gconf2 gconf2-branding-SLES gconf2-lang gcr-data gcr-lang gcr-prompter gd gdb gdk-pixbuf-lang gdk-pixbuf-loader-rsvg gdk-pixbuf-query-loaders gdm gdm-branding-upstream gdm-lang gdmflexiserver gedit gedit-lang genisoimage gettext-runtime gettext-runtime-32bit ghostscript ghostscript-fonts-other ghostscript-fonts-std ghostscript-x11 gio-branding-SLE girepository-1_0 glib-networking glib-networking-lang glib2-lang glib2-tools glibc glibc-32bit glibc-i18ndata glibc-locale glibc-locale-32bit gnome-bluetooth gnome-bluetooth-lang gnome-control-center gnome-control-center-lang gnome-desktop-lang gnome-icon-theme gnome-icon-theme-symbolic gnome-keyring gnome-keyring-lang gnome-keyring-pam gnome-keyring-pam-32bit gnome-menus gnome-menus-branding-SLE gnome-menus-lang gnome-mime-data gnome-nettool gnome-nettool-lang gnome-packagekit gnome-packagekit-lang gnome-power-manager gnome-power-manager-lang gnome-pty-helper gnome-session gnome-session-core gnome-session-default-session gnome-session-lang gnome-settings-daemon gnome-settings-daemon-lang gnome-shell gnome-shell-browser-plugin gnome-shell-classic gnome-shell-extensions-common gnome-shell-extensions-common-lang gnome-shell-lang gnome-shell-search-provider-nautilus gnome-system-monitor gnome-system-monitor-lang gnome-terminal gnome-terminal-lang gnome-themes-accessibility gnome-tweak-tool gnome-tweak-tool-lang gnome-user-docs gnome-user-docs-lang gnome-version gnu-unifont-bitmap-fonts google-opensans-fonts gpart gperftools gpg2 gpg2-lang gpm gpm-32bit gptfdisk graphite-web grep groff groff-full grub2 grub2-branding-SLE grub2-i386-pc grub2-snapper-plugin gsettings-backend-dconf gsettings-desktop-schemas gsettings-desktop-schemas-lang gstreamer gstreamer-lang gstreamer-plugins-bad gstreamer-plugins-bad-lang gstreamer-plugins-base gstreamer-plugins-base-lang gstreamer-plugins-good gstreamer-plugins-good-lang gtk2-branding-SLED gtk2-engine-hcengine gtk2-lang gtk2-metatheme-adwaita gtk2-theming-engine-adwaita gtk2-tools gtk3-data gtk3-lang gtk3-metatheme-adwaita gtk3-theming-engine-adwaita gtk3-tools gucharmap gucharmap-lang gvfs gvfs-backends gvfs-fuse gvfs-lang gxditview gzip hardlink haveged hdparm hicolor-icon-theme hunspell hunspell-tools hwinfo iceauth icedax icewm icewm-lite icewm-theme-branding icmpinfo info info2html initviocons input-utils insserv-compat inst-source-utils intlfonts intlfonts-euro-bitmap-fonts ipmitool iproute2 iptables iputils ipw-firmware irqbalance iscsiuio iso-codes iso-codes-lang iso_ent joe json-glib-lang kbd kdump kernel-default kernel-firmware kexec-tools keyutils kmod kmod-compat kpartx krb5 krb5-32bit latex2html-pngicons less libFLAC8 libGLU1 libHX28 libHX28-32bit libICE6 libICE6-32bit libLLVM libLLVM-32bit libQt5Core5 libQt5DBus5 libQt5Gui5 libQt5Widgets5 libQt5X11Extras5 libSDL-1_2-0 libSM6 libSM6-32bit libSoundTouch0 libX11-6 libX11-6-32bit libX11-data libX11-xcb1 libX11-xcb1-32bit libXRes1 libXau6 libXau6-32bit libXaw3d8 libXaw7 libXcomposite1 libXcursor1 libXcursor1-32bit libXdamage1 libXdamage1-32bit libXdmcp6 libXevie1 libXext6 libXext6-32bit libXfixes3 libXfixes3-32bit libXfont1 libXfontcache1 libXft2 libXft2-32bit libXi6 libXi6-32bit libXinerama1 libXinerama1-32bit libXmu6 libXmuu1 libXpm4 libXrandr2 libXrandr2-32bit libXrender1 libXrender1-32bit libXss1 libXss1-32bit libXt6 libXtst6 libXv1 libXxf86dga1 libXxf86misc1 libXxf86vm1 libXxf86vm1-32bit libaccountsservice0 libacl1 libacl1-32bit libadns1 libaio1 libao-plugins4 libao4 libapparmor1 libapr-util1 libapr1 libarchive13 libasm1 libasound2 libasound2-32bit libaspell15 libass5 libassuan0 libatasmart4 libatk-1_0-0 libatk-1_0-0-32bit libatk-bridge-2_0-0 libatkmm-1_6-1 libatspi0 libattr1 libattr1-32bit libaudiofile1 libaudit1 libaudit1-32bit libaugeas0 libauparse0 libavahi-client3 libavahi-client3-32bit libavahi-common3 libavahi-common3-32bit libavahi-glib1 libbasicobjects0 libblkid1 libblkid1-32bit libbluetooth3 libbluray1 libboost_program_options1_54_0 libboost_regex1_54_0 libboost_system1_54_0 libboost_thread1_54_0 libbrasero-burn3-1 libbrasero-media3-1 libbrasero-utils3-1 libbrlapi0_6 libbtrfs0 libburn4 libbz2-1 libbz2-1-32bit libcairo-gobject2 libcairo2 libcairo2-32bit libcairomm-1_0-1 libcamgm100 libcanberra-gtk3-0 libcanberra0 libcap-ng0 libcap2 libcap2-32bit libcares2 libcaribou0 libcdda_interface0 libcdda_paranoia0 libcdio14 libcdio_cdda1 libcdio_paranoia1 libcelt0-2 libcephfs1 libcheese-common libcheese-gtk23 libcheese7 libcloog-isl4 libclutter-1_0-0 libclutter-gst-2_0-0 libclutter-gtk-1_0-0 libcogl-pango15 libcogl15 libcollection2 libcolord-gtk1 libcolord2 libcom_err2 libcom_err2-32bit libcpupower0 libcrack2 libcrack2-32bit libcroco-0_6-3 libcroco-0_6-3-32bit libcryptmount0 libcryptmount0-32bit libcryptsetup4 libcryptsetup4-32bit libcurl4 libcurl4-32bit libdb-4_8 libdb-4_8-32bit libdbus-1-3 libdbus-1-3-32bit libdcerpc-binding0 libdcerpc-binding0-32bit libdcerpc0 libdcerpc0-32bit libdconf1 libdhash1 libdialog11 libdjvulibre21 libdm0 libdmx1 libdotconf0 libdrm2 libdrm2-32bit libdrm_intel1 libdrm_intel1-32bit libdrm_nouveau2 libdrm_nouveau2-32bit libdrm_radeon1 libdrm_radeon1-32bit libdv4 libdvdnav4 libdvdread4 libdw1 libedit0 libelf0 libelf1 libelf1-32bit libenca0 libenchant1 libesd0 libesmtp libestr0 libevdev2 libevdocument3-4 libevent-2_0-5 libevview3-3 libexempi3 libexif12 libexpat1 libexpat1-32bit libext2fs2 libfam0-gamin libffi4 libffi4-32bit libfftw3-3 libfipscheck1 libfipscheck1-32bit libfltk1 libfontenc1 libfreebl3 libfreebl3-32bit libfreetype6 libfreetype6-32bit libftgl2 libfuse2 libgbm1 libgbm1-32bit libgc1 libgcc_s1 libgcc_s1-32bit libgck-1-0 libgck-modules-gnome-keyring libgcr-3-1 libgcrypt20 libgcrypt20-32bit libgdbm4 libgdbm4-32bit libgdk_pixbuf-2_0-0 libgdm1 libgee-0_8-2 libgensec0 libgensec0-32bit libgeoclue0 libgeocode-glib0 libgif6-32bit libgio-2_0-0 libgio-2_0-0-32bit libgiomm-2_4-1 libgirepository-1_0-1 libgjs0 libglade-2_0-0 libglib-2_0-0 libglib-2_0-0-32bit libglibmm-2_4-1 libgme0 libgmime-2_6-0 libgmodule-2_0-0 libgmodule-2_0-0-32bit libgmp10 libgnome-bluetooth12 libgnome-desktop-3-8 libgnome-desktop-3_0-common libgnome-keyring-lang libgnome-keyring0 libgnome-menu-3-0 libgnomesu libgnomesu-lang libgnomesu0 libgnutls28 libgoa-1_0-0 libgoa-backend-1_0-1 libgobject-2_0-0 libgobject-2_0-0-32bit libgpg-error0 libgpg-error0-32bit libgpgme11 libgphoto2-6 libgphoto2-6-lang libgraphite2-3 libgraphite2-3-32bit libgsm1 libgssglue1 libgstallocators-1_0-0 libgstapp-1_0-0 libgstaudio-1_0-0 libgstbasecamerabinsrc-1_0-0 libgstcodecparsers-1_0-0 libgstegl-1_0-0 libgstfft-1_0-0 libgstmpegts-1_0-0 libgstpbutils-1_0-0 libgstphotography-1_0-0 libgstreamer-1_0-0 libgstriff-1_0-0 libgstrtp-1_0-0 libgstrtsp-1_0-0 libgstsdp-1_0-0 libgsttag-1_0-0 libgstvideo-1_0-0 libgthread-2_0-0 libgtk-2_0-0 libgtk-3-0 libgtkmm-3_0-1 libgtksourceview-3_0-1 libgtop-2_0-10 libgtop-lang libgucharmap_2_90-7 libgudev-1_0-0 libgvfscommon0 libgweather-3-6 libgweather-data libgweather-lang libgxps2 libharfbuzz-icu0 libharfbuzz0 libharfbuzz0-32bit libhavege1 libhogweed2 libibus-1_0-5 libical1 libicu52_1 libicu52_1-data libidn-tools libidn11 libidn11-32bit libimobiledevice4 libini_config3 libiptc0 libisl10 libisofs6 libiw30 libjack0 libjasper1 libjavascriptcoregtk-3_0-0 libjbig2 libjbig2-32bit libjpeg8 libjpeg8-32bit libjson-c2 libjson-glib-1_0-0 libkate1 libkeyutils1 libkeyutils1-32bit libkmod2 libkpathsea6 libksba8 liblcms1 liblcms1-32bit liblcms2-2 libldap-2_4-2 libldap-2_4-2-32bit libldapcpp1 libldb1 libldb1-32bit libleveldb1 liblockdev1 liblogging0 liblouis2 liblrdf2 libltdl7 liblua5_1 liblua5_1-32bit liblua5_2 liblzma5 liblzma5-32bit liblzo2-2 libmagic1 libmagic1-32bit libmjpegutils-2_0-0 libmm-glib0 libmms0 libmng1 libmng1-32bit libmnl0 libmodman1 libmodplug1 libmount1 libmount1-32bit libmozjs-17_0 libmpc3 libmpfr4 libmtdev1 libmtp9 libmutter0 libmysqlclient18 libnautilus-extension1 libncurses5 libncurses5-32bit libncurses6 libndr-krb5pac0 libndr-krb5pac0-32bit libndr-nbt0 libndr-nbt0-32bit libndr-standard0 libndr-standard0-32bit libndr0 libndr0-32bit libneon27 libnetapi0 libnetapi0-32bit libnetfilter_conntrack3 libnetpbm11 libnettle4 libnfnetlink0 libnl-config libnl1 libnl3-200 libnm-glib-vpn1 libnm-glib4 libnm-gtk0 libnm-util2 libnotify4 libnscd1 libnscd1-32bit libnsssharedhelper0 libnuma1 libofa0 libogg0 liboggkate1 libopenct1 libopenssl1_0_0 libopenssl1_0_0-32bit libopus0 liborc-0_4-0 libp11-kit0 libpackagekit-glib2-16 libpango-1_0-0 libpango-1_0-0-32bit libpangomm-1_4-1 libparted0 libpath_utils1 libpcap1 libpci3 libpci3-32bit libpciaccess0 libpciaccess0-32bit libpcre1 libpcre1-32bit libpcre16-0 libpdb0 libpdb0-32bit libpeas-1_0-0 libpeas-gtk-1_0-0 libpipeline1 libpixman-1-0 libpixman-1-0-32bit libplist1 libply-boot-client2 libply-splash-core2 libply-splash-graphics2 libply2 libpng16-16 libpng16-16-32bit libpolkit0 libpoppler-glib8 libpoppler44 libpopt0 libpopt0-32bit libportaudio2 libpq5 libprocps3 libproxy1 libproxy1-config-gnome3 libpth20 libpulse-mainloop-glib0 libpulse0 libpwquality-lang libpwquality1 libpyglib-gi-2_0-python2-0 libpyglib-gi-2_0-python3-0 libpython2_7-1_0 libpython2_7-1_0-32bit libpython3_4m1_0 libqpdf13 libqrencode3 libqt4 libqt4-32bit libqt4-sql libqt4-sql-32bit libqt4-sql-mysql libqt4-x11 libqt4-x11-32bit libquicktime0 libquvi libquvi-scripts librados2 libraptor2-0 librbd1 libreadline6 libref_array1 libregistry0 libreiserfscore0 librest0 librpcsecgss3 librsvg-2-2 libruby2_1-2_1 libsamba-credentials0 libsamba-credentials0-32bit libsamba-hostconfig0 libsamba-hostconfig0-32bit libsamba-util0 libsamba-util0-32bit libsamdb0 libsamdb0-32bit libsamplerate0 libsasl2-3 libsasl2-3-32bit libschroedinger-1_0-0 libseccomp2 libsecret-1-0 libsecret-lang libselinux1 libselinux1-32bit libsemanage1 libsemanage1-32bit libsensors4 libsepol1 libsepol1-32bit libsgutils2-2 libsigc-2_0-0 libslang2 libsmartcols1 libsmbclient-raw0 libsmbclient-raw0-32bit libsmbclient0 libsmbconf0 libsmbconf0-32bit libsmbldap0 libsmbldap0-32bit libsmi libsmi2 libsnapper2 libsnappy1 libsndfile1 libsnmp30 libsoftokn3 libsoftokn3-32bit libsolv-tools libsoup-2_4-1 libsoup-lang libspandsp2 libspectre1 libspeechd2 libspeex1 libspeexdsp1 libsqlite3-0 libsqlite3-0-32bit libssh2-1 libssh2-1-32bit libsss_idmap0 libstartup-notification-1-0 libstdc++6 libstdc++6-32bit libstorage-ruby libstorage5 libstroke libtag1 libtalloc2 libtalloc2-32bit libtasn1 libtasn1-6 libtdb1 libtdb1-32bit libtelepathy-glib0 libtelepathy-logger3 libtevent-util0 libtevent-util0-32bit libtevent0 libtevent0-32bit libtheora0 libtiff5 libtiff5-32bit libtirpc1 libtool libtool-32bit libtotem-plparser18 libtracker-common-0_16-0 libtracker-sparql-0_16-0 libttf2 libudev1 libudev1-32bit libudisks2-0 libunwind libunwind-devel libupower-glib3 libusb-0_1-4 libusb-1_0-0 libusbmuxd2 libustr-1_0-1 libustr-1_0-1-32bit libutempter0 libuuid1 libuuid1-32bit libv4l libv4l1-0 libv4l2-0 libv4lconvert0 libvdpau1 libvisual libvorbis0 libvorbisenc2 libvorbisfile3 libvpx1 libvte2_90-9 libwacom-data libwacom2 libwavpack1 libwbclient0 libwbclient0-32bit libwebkitgtk-3_0-0 libwebkitgtk3-lang libwebp5 libwebpmux1 libwebrtc_audio_processing0 libwicked-0-6 libwnck-3-0 libwnck-lang libwrap0 libwrap0-32bit libx86emu1 libxcb-dri2-0 libxcb-dri2-0-32bit libxcb-glx0 libxcb-glx0-32bit libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-render0 libxcb-render0-32bit libxcb-shape0 libxcb-shm0 libxcb-shm0-32bit libxcb-sync1 libxcb-util1 libxcb-xfixes0 libxcb-xfixes0-32bit libxcb-xkb1 libxcb-xv0 libxcb1 libxcb1-32bit libxkbcommon-x11-0 libxkbcommon0 libxkbfile1 libxklavier16 libxml2-2 libxml2-2-32bit libxml2-tools libxshmfence1 libxslt-tools libxslt1 libxtables10 libyaml-0-2 libyelp0 libyui-ncurses-pkg6 libyui-ncurses6 libyui-qt-pkg6 libyui-qt6 libyui6 libz1 libz1-32bit libzio1 libzmq3 libzypp listres lockdev logrotate lsb-release lsof lsscsi lua luasocket luit lvm2 m4 mailx make makedumpfile man man-pages man-pages-posix master-boot-code mc mc-lang mcelog mdadm metamail metatheme-adwaita-common mingetty mkfontdir mkfontscale mksh mlocate mozilla-nspr mozilla-nspr-32bit mozilla-nss mozilla-nss-32bit mozilla-nss-certs mozilla-nss-certs-32bit mpt-firmware mtools multipath-tools mutt mutter mutter-data mutter-lang nano nautilus nautilus-file-roller nautilus-lang nautilus-open-terminal nautilus-open-terminal-lang nautilus-share nautilus-share-lang ncurses-utils net-snmp net-tools netcat-openbsd netcfg netpbm nfs-client nfs-doc nfs-kernel-server nfsidmap notification-daemon notification-daemon-lang novell-sound-theme nscd ntp numactl ofl open-iscsi openct openldap2-client opensc openslp openslp-32bit openslp-server openssh openssh-askpass openssh-helpers openssl opie opie-32bit orca orca-lang os-prober p11-kit p11-kit-tools p7zip pam pam-32bit pam-config pam-doc pam-modules pam-modules-32bit pam_mount pam_mount-32bit pango-modules pango-modules-32bit parted patch patterns-sle-gnome-basic patterns-sles-32bit patterns-sles-Minimal patterns-sles-Minimal-32bit patterns-sles-apparmor patterns-sles-apparmor-32bit patterns-sles-base patterns-sles-base-32bit patterns-sles-documentation patterns-sles-documentation-32bit patterns-sles-x11 patterns-sles-x11-32bit pax pciutils pciutils-ids pcsc-lite perl perl-32bit perl-Bit-Vector perl-Bootloader perl-Bootloader-YAML perl-Carp-Clan perl-Config-Crontab perl-Config-IniFiles perl-Crypt-SmbHash perl-DBD-SQLite perl-DBI perl-Date-Calc perl-Digest-HMAC perl-Digest-MD4 perl-Digest-SHA1 perl-Encode-Locale perl-File-Listing perl-HTML-Parser perl-HTML-Tagset perl-HTTP-Cookies perl-HTTP-Daemon perl-HTTP-Date perl-HTTP-Message perl-HTTP-Negotiate perl-IO-HTML perl-IO-Socket-SSL perl-LWP-MediaTypes perl-LWP-Protocol-https perl-List-MoreUtils perl-Net-DBus perl-Net-DNS perl-Net-Daemon perl-Net-HTTP perl-Net-SSLeay perl-Parse-RecDescent perl-PlRPC perl-RPC-XML perl-SNMP perl-Sub-Uplevel perl-Term-ReadKey perl-Test-Exception perl-Tie-IxHash perl-TimeDate perl-URI perl-WWW-RobotRules perl-X11-Protocol perl-X500-DN perl-XML-LibXML perl-XML-NamespaceSupport perl-XML-Parser perl-XML-SAX perl-XML-SAX-Base perl-XML-SAX-Expat perl-XML-Simple perl-XML-Twig perl-XML-Writer perl-XML-XPath perl-XML-XPathEngine perl-YAML-LibYAML perl-apparmor perl-base perl-camgm perl-gettext perl-libwww-perl permissions pigz pinentry pkg-config plymouth plymouth-branding-SLE plymouth-dracut plymouth-plugin-label plymouth-plugin-script plymouth-scripts polkit polkit-default-privs polkit-gnome polkit-gnome-lang poppler-data poppler-tools postfix postgresql-init postgresql93 postgresql93-server ppp pptp prctl procinfo procmail procps psmisc psmisc-lang psutils pulseaudio pulseaudio-esound-compat pulseaudio-lang pulseaudio-module-x11 pulseaudio-utils pytalloc pytalloc-32bit python python-Django python-Flask python-Jinja2 python-M2Crypto python-Mako python-MarkupSafe python-Pillow python-PyYAML python-SQLAlchemy python-Twisted python-Werkzeug python-alembic python-apache-libcloud python-argparse python-base python-cairo python-carbon python-ceph python-cffi python-cryptography python-cups python-cupshelpers python-dateutil python-django-tagging python-djangorestframework python-ecdsa python-execnet python-gevent python-gobject python-gobject-cairo python-greenlet python-itsdangerous python-lxml python-msgpack-python python-pam python-paramiko python-psutil python-psycogreen python-psycopg2 python-pushy python-pyOpenSSL python-pycparser python-pycrypto python-pycurl python-pyparsing python-pyserial python-pytz python-pyzmq python-remoto python-requests python-setuptools python-simplejson python-six python-smbc python-solv python-whisper python-xml python-zerorpc python-zope.interface python3 python3-atspi python3-base python3-brlapi python3-cairo python3-gedit python3-gobject python3-louis python3-speechd quota readline-doc recode reiserfs release-notes-sles rendercheck rgb rpcbind rpm rpm-32bit rpm-python rsh rsync rsyslog rtkit ruby ruby-common ruby2.1 ruby2.1-rubygem-fast_gettext ruby2.1-rubygem-gem2rpm ruby2.1-rubygem-ruby-dbus ruby2.1-rubygem-suse-connect ruby2.1-stdlib salt salt-master salt-minion samba samba-32bit samba-client samba-client-32bit samba-libs samba-libs-32bit scout screen sed sed-lang sessreg setxkbmap sg3_utils sgml-skel shadow shared-mime-info sharutils sharutils-lang sles-admin_en-pdf sles-deployment_en-pdf sles-installquick_en-pdf sles-manuals_en sles-release sles-security_en-pdf sles-storage_en-pdf sles-tuning_en-pdf smartmontools snapper snapper-zypp-plugin snmp-mibs sound-theme-freedesktop speech-dispatcher speech-dispatcher-module-espeak sqlite3 sssd sssd-32bit sssd-krb5-common sssd-ldap star strace strace-32bit sudo supportutils suse-build-key suse-module-tools susehelp susehelp_en sysconfig sysconfig-netconfig sysfsutils sysfsutils-32bit syslinux syslog-service system-config-printer-common system-config-printer-common-lang system-config-printer-dbus-service systemd systemd-32bit systemd-bash-completion systemd-presets-branding-SLE systemd-sysvinit sysvinit-tools tar tar-lang tcl tcl-32bit tcpd tcpdump tcsh telnet terminfo terminfo-base tigervnc time timezone tk tk-32bit totem-pl-parser totem-pl-parser-lang traceroute typelib-1_0-AccountsService-1_0 typelib-1_0-Atk-1_0 typelib-1_0-Atspi-2_0 typelib-1_0-Caribou-1_0 typelib-1_0-Clutter-1_0 typelib-1_0-Cogl-1_0 typelib-1_0-CoglPango-1_0 typelib-1_0-GMenu-3_0 typelib-1_0-Gck-1 typelib-1_0-Gcr-3 typelib-1_0-GdkPixbuf-2_0 typelib-1_0-Gdm-1_0 typelib-1_0-GjsPrivate-1_0 typelib-1_0-GnomeBluetooth-1_0 typelib-1_0-GnomeDesktop-3_0 typelib-1_0-GnomeKeyring-1_0 typelib-1_0-Gtk-3_0 typelib-1_0-GtkSource-3_0 typelib-1_0-IBus-1_0 typelib-1_0-Json-1_0 typelib-1_0-Meta-3_0 typelib-1_0-NMClient-1_0 typelib-1_0-NMGtk-1_0 typelib-1_0-NetworkManager-1_0 typelib-1_0-Notify-0_7 typelib-1_0-PackageKitGlib-1_0 typelib-1_0-Pango-1_0 typelib-1_0-Peas-1_0 typelib-1_0-PeasGtk-1_0 typelib-1_0-Polkit-1_0 typelib-1_0-Soup-2_4 typelib-1_0-TelepathyGlib-0_12 typelib-1_0-TelepathyLogger-0_2 typelib-1_0-UpowerGlib-1_0 typelib-1_0-Wnck-3_0 ucode-intel udev udev-configure-printer udisks2 udisks2-lang unclutter unrar unzip update-alternatives upower upower-lang usbmuxd usbutils util-linux util-linux-lang util-linux-systemd viewres vim vim-data vino vino-lang vlan vlock vorbis-tools vorbis-tools-lang vsftpd vte-lang w3m wallpaper-branding-SLE wget which wicked wicked-service wireless-tools wodim x11-tools x11perf x86info xauth xbacklight xbitmaps xclock xconsole xcursor-themes xcursorgen xdg-menu xdg-user-dirs xdg-user-dirs-gtk xdg-user-dirs-gtk-lang xdg-user-dirs-lang xdg-utils xdm xdmbgrd xdpyinfo xev xeyes xf86-input-evdev xf86-input-synaptics xf86-input-vmmouse xf86-input-void xf86-input-wacom xf86-video-fbdev xf86-video-mga xf86-video-modesetting xf86-video-vesa xfd xfontsel xfsprogs xgamma xhost xinetd xinit xinput xkbcomp xkbevd xkbprint xkbutils xkeyboard-config xkeyboard-config-lang xkill xlockmore xlogo xlsatoms xlsclients xlsfonts xmag xmessage xmodmap xorg-x11 xorg-x11-Xvnc xorg-x11-driver-video xorg-x11-essentials xorg-x11-fonts xorg-x11-fonts-core xorg-x11-libs xorg-x11-server xorg-x11-server-extra xprop xrandr xrdb xrestop xscope xscreensaver xscreensaver-data xset xsetmode xsetpointer xsetroot xtables-plugins xterm xtermset xvinfo xwd xwininfo xz xz-lang yast2 yast2-add-on yast2-apparmor yast2-audit-laf yast2-auth-client yast2-auth-server yast2-boot-server yast2-bootloader yast2-branding-SLE yast2-ca-management yast2-control-center yast2-control-center-gnome yast2-core yast2-country yast2-country-data yast2-dhcp-server yast2-dns-server yast2-firewall yast2-ftp-server yast2-hardware-detection yast2-http-server yast2-inetd yast2-installation yast2-instserver yast2-iscsi-client yast2-isns yast2-kdump yast2-ldap yast2-mail yast2-metapackage-handler yast2-network yast2-nfs-client yast2-nfs-common yast2-nfs-server yast2-nis-client yast2-nis-server yast2-ntp-client yast2-online-update yast2-online-update-frontend yast2-packager yast2-pam yast2-perl-bindings yast2-pkg-bindings yast2-printer yast2-proxy yast2-registration yast2-ruby-bindings yast2-samba-client yast2-samba-server yast2-schema yast2-security yast2-services-manager yast2-slp yast2-snapper yast2-sound yast2-squid yast2-storage yast2-sudo yast2-support yast2-sysconfig yast2-tftp-server yast2-theme-SLE yast2-trans-en_US yast2-trans-stats yast2-transfer yast2-update yast2-users yast2-vm yast2-x11 yast2-xml yast2-ycp-ui-bindings yelp yelp-lang yelp-xsl yp-tools ypbind zenity zenity-lang zip zisofs-tools zsh zypp-plugin-python zypper zypper-log zypper
Specified path '/home/col/down' is not a directory: dir:///home/col/down

Specified path '/home/col/down' is not a directory: dir:///home/col/down

Specified path '/home/col/down' is not a directory: dir:///home/col/down

Repository 'ceph_disk1' is invalid.
[ceph_disk1|iso:///?iso=/home/col/down/SUSE-Enterprise-Storage-1.0-DVD-x86_64-Build0131-Media1.iso] Valid metadata not found at specified URL
Please check if the URIs defined for this repository are pointing to a valid repository.
Problem loading data from 'ceph_disk1'
Resolvables from 'ceph_disk1' not loaded because of error.
Specified path '/home/col/down' is not a directory: dir:///home/col/down

Repository 'ceph_disk2' is invalid.
[ceph_disk2|iso:///?iso=/home/col/down/SUSE-Enterprise-Storage-1.0-DVD-x86_64-Build0131-Media2.iso] Valid metadata not found at specified URL
Please check if the URIs defined for this repository are pointing to a valid repository.
Problem loading data from 'ceph_disk2'
Resolvables from 'ceph_disk2' not loaded because of error.
Package 'apache2-mod_wsgi' not found.
Package 'python-Django' not found.
Package 'python-Flask' not found.
Package 'python-Jinja2' not found.
Package 'python-Mako' not found.
Package 'python-MarkupSafe' not found.
Package 'python-Pillow' not found.
Package 'python-PyYAML' not found.
Package 'python-SQLAlchemy' not found.
Package 'python-Twisted' not found.
Package 'python-Werkzeug' not found.
Package 'python-alembic' not found.
Package 'python-apache-libcloud' not found.
Package 'python-carbon' not found.
Package 'python-dateutil' not found.
Package 'python-django-tagging' not found.
Package 'python-djangorestframework' not found.
Package 'python-ecdsa' not found.
Package 'python-execnet' not found.
Package 'python-gevent' not found.
Package 'python-greenlet' not found.
Package 'python-itsdangerous' not found.
Package 'python-msgpack-python' not found.
Package 'python-paramiko' not found.
Package 'python-psutil' not found.
Package 'python-psycogreen' not found.
Package 'python-psycopg2' not found.
Package 'python-pushy' not found.
Package 'python-pycrypto' not found.
Package 'python-pyserial' not found.
Package 'python-pytz' not found.
Package 'python-pyzmq' not found.
Package 'python-remoto' not found.
Package 'python-setuptools' not found.
Package 'python-whisper' not found.
Package 'python-zerorpc' not found.
Package 'python-zope.interface' not found.
No provider of 'ceph' found.
No provider of 'calamari-clients' found.
No provider of 'calamari-server' found.
No provider of 'ceph-deploy' found.
No provider of 'graphite-web' found.
No provider of 'libleveldb1' found.
No provider of 'libwebpmux1' found.
No provider of 'libzmq3' found.
No provider of 'nano' found.
No provider of 'salt' found.
No provider of 'salt-master' found.
No provider of 'salt-minion' found.
Building the Image with Kiwi failed.
The Kiwi build directory /tmp/machinery-image20150624-5413-k2qelu was not removed.
The image build process failed. Check build log '/tmp/machinery-image20150624-5413-k2qelu/kiwi-terminal-output.log' for more details.
peon@dhcp110:~> more /tmp/machinery-image20150624-5413-k2qelu/kiwi-terminal-output.log 
Jun-24 15:18:00 <1> : kiwi --build /tmp/machinery-config20150624-5413-tb6rml --destdir /tmp/machinery-image20150624-5413-k2qelu --logfile /tmp/machinery-image20150624-5413-k
2qelu/kiwi-terminal-output.log
Jun-24 15:18:00 <1> : kiwi revision: 75b17ac4122bc096e47a77ecd91f1ddb91862cf4
Jun-24 15:18:00 <1> : Setting log file to: /tmp/machinery-image20150624-5413-k2qelu/kiwi-terminal-output.log
Jun-24 15:18:00 <1> : Destination: /tmp/machinery-image20150624-5413-k2qelu/build doesn't exist
Jun-24 15:18:00 <1> : EXEC [mkdir -p /tmp/machinery-image20150624-5413-k2qelu/build]
Jun-24 15:18:00 <1> : EXEC [/usr/bin/uname -m]
Jun-24 15:18:02 <1> : EXEC [/usr/bin/uname -m]
Jun-24 15:18:04 <1> : Description provides no MD5 hash, check
Jun-24 15:18:04 <1> : Reading image description [Prepare]...
Jun-24 15:18:04 <1> : EXEC [/usr/bin/uname -m]
Jun-24 15:18:06 <1> : EXEC [rm -f /var/cache/kiwi/zypper/repos/* 2>&1]
Jun-24 15:18:06 <1> : Setting up package manager: 
zypper
Jun-24 15:18:06 <1> : Setting up source channel:
Jun-24 15:18:06 <1> : --> nfs://10.160.0.100/dist/install/SLP/SLE-12-Server-GM/x86_64/DVD1
Jun-24 15:18:06 <1> : Setting up source channel:
Jun-24 15:18:06 <1> : --> https://updates.suse.com/SUSE/Products/SLE-SERVER/12/x86_64/product?AUTRkVHSnJTjJMEzw7JDFKrgoYUsDd_8iVRGRjNMjQtyRYNNkm1hrmkfFSzi1LV7ht8G2ZLYJ7JcIaW
b0wNDhAfsTUdb4UokRRcqDdi0g0eBvXMWIosjXjKzVOXZ1Bn4BUYtkPRJw2y-
Jun-24 15:18:06 <1> : Setting up source channel:
Jun-24 15:18:06 <1> : --> https://updates.suse.com/SUSE/Updates/SLE-SERVER/12/x86_64/update?lakSMlU5hO4IXHpigk0OwxJUl9ecYgCcIRC0urxttkTAlLjx5_mjx0-yX2SG2bA5jBQD8PC69zycfftm6
Ofp2Z46RPO5c_pMuCoBrAZmiQEw-Lg6fr3fiEDBtNmJCIL4r0JN1Ngp9w
Jun-24 15:18:06 <1> : Setting up source channel:
Jun-24 15:18:06 <1> : --> iso:///?iso=/home/col/down/SUSE-Enterprise-Storage-1.0-DVD-x86_64-Build0131-Media1.iso
Jun-24 15:18:06 <1> : Setting up source channel:
Jun-24 15:18:06 <1> : --> iso:///?iso=/home/col/down/SUSE-Enterprise-Storage-1.0-DVD-x86_64-Build0131-Media2.iso
Jun-24 15:18:06 <1> : EXEC [touch /tmp/machinery-image20150624-5413-k2qelu/build/image-root/.broken 2>&1]
Jun-24 15:18:06 <1> : EXEC [mkdir -p /var/cache/kiwi/zypper]
Jun-24 15:18:06 <1> : EXEC [echo '[main]' > /var/cache/kiwi/zypper/zypper.conf.5428]
Jun-24 15:18:06 <1> : EXEC [echo '[main]' > /var/cache/kiwi/zypper/zypp.conf.5428]
Jun-24 15:18:06 <1> : Creating credentials data
Jun-24 15:18:06 <1> : EXEC [mkdir -p /tmp/machinery-image20150624-5413-k2qelu/build/image-root/etc]
Jun-24 15:18:06 <1> : EXEC [chown root:root /tmp/machinery-image20150624-5413-k2qelu/build/image-root/etc]
Jun-24 15:18:06 <1> : EXEC [cp /usr/share/kiwi/modules/KIWIConfig.sh /tmp/machinery-image20150624-5413-k2qelu/build/image-root/.kconfig 2>&1]
Jun-24 15:18:06 <1> : EXEC [cp /etc/resolv.conf /tmp/machinery-image20150624-5413-k2qelu/build/image-root/etc 2>&1]
Jun-24 15:18:06 <1> : EXEC [cp /etc/hosts /tmp/machinery-image20150624-5413-k2qelu/build/image-root/etc 2>&1]
Jun-24 15:18:06 <1> : EXEC [mkdir -p /tmp/machinery-image20150624-5413-k2qelu/build/image-root/etc/sysconfig 2>&1]
Jun-24 15:18:06 <1> : EXEC [cp /etc/sysconfig/proxy /tmp/machinery-image20150624-5413-k2qelu/build/image-root/etc/sysconfig 2>&1]
Jun-24 15:18:06 <1> : Set package manager lock
Jun-24 15:18:06 <1> : EXEC [touch /var/lock/kiwi-init.lock]
Jun-24 15:18:06 <1> : Creating default template files for new root system
Jun-24 15:18:06 <1> : EXEC [mkdir -p /tmp/machinery-image20150624-5413-k2qelu/build/image-root/dev]
Jun-24 15:18:06 <1> : EXEC [chown root:root /tmp/machinery-image20150624-5413-k2qelu/build/image-root/dev]
Jun-24 15:18:06 <1> : EXEC [mkdir -m 755 -p /tmp/machinery-image20150624-5413-k2qelu/build/image-root/proc]
Jun-24 15:18:06 <1> : EXEC [chown root:root /tmp/machinery-image20150624-5413-k2qelu/build/image-root/proc]
Jun-24 15:18:06 <1> : EXEC [mkdir -m 755 -p /tmp/machinery-image20150624-5413-k2qelu/build/image-root/dev/pts]
Jun-24 15:18:06 <1> : EXEC [mknod -m 666 /tmp/machinery-image20150624-5413-k2qelu/build/image-root/dev/null c 1 3]
Jun-24 15:18:06 <1> : EXEC [mknod -m 666 /tmp/machinery-image20150624-5413-k2qelu/build/image-root/dev/zero c 1 5]
Jun-24 15:18:06 <1> : EXEC [mknod -m 622 /tmp/machinery-image20150624-5413-k2qelu/build/image-root/dev/full c 1 7]
Jun-24 15:18:06 <1> : EXEC [mknod -m 666 /tmp/machinery-image20150624-5413-k2qelu/build/image-root/dev/random c 1 8]
Jun-24 15:18:06 <1> : EXEC [mknod -m 644 /tmp/machinery-image20150624-5413-k2qelu/build/image-root/dev/urandom c 1 9]
Jun-24 15:18:06 <1> : EXEC [mknod -m 666 /tmp/machinery-image20150624-5413-k2qelu/build/image-root/dev/tty c 5 0]
Jun-24 15:18:06 <1> : EXEC [mknod -m 666 /tmp/machinery-image20150624-5413-k2qelu/build/image-root/dev/ptmx c 5 2]
Jun-24 15:18:06 <1> : EXEC [ln -s /proc/self/fd /tmp/machinery-image20150624-5413-k2qelu/build/image-root/dev/fd]
Jun-24 15:18:06 <1> : EXEC [ln -s fd/2 /tmp/machinery-image20150624-5413-k2qelu/build/image-root/dev/stderr]
Jun-24 15:18:06 <1> : EXEC [ln -s fd/0 /tmp/machinery-image20150624-5413-k2qelu/build/image-root/dev/stdin]
Jun-24 15:18:06 <1> : EXEC [ln -s fd/1 /tmp/machinery-image20150624-5413-k2qelu/build/image-root/dev/stdout]
Jun-24 15:18:06 <1> : EXEC [mknod -m 640 /tmp/machinery-image20150624-5413-k2qelu/build/image-root/dev/loop0 b 7 0]
Jun-24 15:18:06 <1> : EXEC [mknod -m 640 /tmp/machinery-image20150624-5413-k2qelu/build/image-root/dev/loop1 b 7 1]
Jun-24 15:18:06 <1> : EXEC [mknod -m 640 /tmp/machinery-image20150624-5413-k2qelu/build/image-root/dev/loop2 b 7 2]
Jun-24 15:18:06 <1> : EXEC [mknod -m 640 /tmp/machinery-image20150624-5413-k2qelu/build/image-root/dev/loop3 b 7 3]
Jun-24 15:18:06 <1> : EXEC [mkdir -p /tmp/machinery-image20150624-5413-k2qelu/build/image-root/etc/sysconfig]
Jun-24 15:18:06 <1> : EXEC [mkdir -m 755 -p /tmp/machinery-image20150624-5413-k2qelu/build/image-root/var]
Jun-24 15:18:06 <1> : EXEC [chown root:root /tmp/machinery-image20150624-5413-k2qelu/build/image-root/var]
Jun-24 15:18:06 <1> : EXEC [mkdir -p /tmp/machinery-image20150624-5413-k2qelu/build/image-root/var/log/YaST2]
Jun-24 15:18:06 <1> : EXEC [touch /tmp/machinery-image20150624-5413-k2qelu/build/image-root/etc/sysconfig/bootloader]
Jun-24 15:18:06 <1> : EXEC [cp /var/adm/fillup-templates/group.aaa_base /tmp/machinery-image20150624-5413-k2qelu/build/image-root/etc/group  2>&1]
Jun-24 15:18:06 <1> : EXEC [cp /var/adm/fillup-templates/passwd.aaa_base /tmp/machinery-image20150624-5413-k2qelu/build/image-root/etc/passwd 2>&1]
Jun-24 15:18:06 <1> : Importing build keys...
Jun-24 15:18:06 <1> : EXEC [mkdir -p /tmp/machinery-image20150624-5413-k2qelu/build/image-root/rpm-sigs && cp -a /usr/lib/rpm/gnupg/keys/* /tmp/machinery-image20150624-5413-
k2qelu/build/image-root/rpm-sigs]
Jun-24 15:18:06 <1> : EXEC [rpm -r /tmp/machinery-image20150624-5413-k2qelu/build/image-root --import /tmp/machinery-image20150624-5413-k2qelu/build/image-root/rpm-sigs/gpg-
pubke* 2>&1]
Jun-24 15:18:06 <1> : EXEC [rm -rf /tmp/machinery-image20150624-5413-k2qelu/build/image-root/rpm-sigs]
Jun-24 15:18:06 <1> : EXEC [mkdir -p /tmp/machinery-image20150624-5413-k2qelu/build/image-root/dev]
Jun-24 15:18:06 <1> : EXEC [mount -n --bind /dev /tmp/machinery-image20150624-5413-k2qelu/build/image-root/dev]
Jun-24 15:18:06 <1> : EXEC [cat /proc/mounts | grep /tmp/machinery-image20150624-5413-k2qelu/build/image-root/var/cache/kiwi 2>&1]
Jun-24 15:18:06 <1> : EXEC [mkdir -p /tmp/machinery-image20150624-5413-k2qelu/build/image-root//var/cache/kiwi 2>&1]
Jun-24 15:18:06 <1> : EXEC [mount -n --bind /var/cache/kiwi /tmp/machinery-image20150624-5413-k2qelu/build/image-root//var/cache/kiwi 2>&1]
Jun-24 15:18:06 <1> : EXEC [mkdir -p /tmp/machinery-image20150624-5413-k2qelu/build/image-root/proc]
Jun-24 15:18:06 <1> : EXEC [mount -n -t proc proc /tmp/machinery-image20150624-5413-k2qelu/build/image-root/proc]
Jun-24 15:18:06 <1> : EXEC [test -f /tmp/machinery-image20150624-5413-k2qelu/build/image-root//var/cache/kiwi/zypper/repos/SUSE_Linux_Enterprise_Server_12_x86_64:SLES12-Upda
tes.repo]
Jun-24 15:18:06 <1> : Adding bootstrap zypper service: SUSE_Linux_Enterprise_Server_12_x86_64:SLES12-Updates
Jun-24 15:18:06 <1> : EXEC [/usr/bin/zypper --non-interactive --pkg-cache-dir /var/cache/kiwi/packages --reposd-dir /tmp/machinery-image20150624-5413-k2qelu/build/image-root
//var/cache/kiwi/zypper/repos --solv-cache-dir /tmp/machinery-image20150624-5413-k2qelu/build/image-root//var/cache/kiwi/zypper/solv --cache-dir /tmp/machinery-image20150624
-5413-k2qelu/build/image-root//var/cache/kiwi/zypper --config /var/cache/kiwi/zypper/zypper.conf.5428 --no-gpg-checks --root "/tmp/machinery-image20150624-5413-k2qelu/build/
image-root" addrepo -f --type YUM --keep-packages 'https://updates.suse.com/SUSE/Updates/SLE-SERVER/12/x86_64/update?lakSMlU5hO4IXHpigk0OwxJUl9ecYgCcIRC0urxttkTAlLjx5_mjx0-y
X2SG2bA5jBQD8PC69zycfftm6Ofp2Z46RPO5c_pMuCoBrAZmiQEw-Lg6fr3fiEDBtNmJCIL4r0JN1Ngp9w?credentials=kiwiRepoCredentials' SUSE_Linux_Enterprise_Server_12_x86_64:SLES12-Updates 2>&
1]
Jun-24 15:18:06 <1> : --> Set priority to: 99
Jun-24 15:18:06 <1> : EXEC [/usr/bin/zypper --non-interactive --pkg-cache-dir /var/cache/kiwi/packages --reposd-dir /tmp/machinery-image20150624-5413-k2qelu/build/image-root
//var/cache/kiwi/zypper/repos --solv-cache-dir /tmp/machinery-image20150624-5413-k2qelu/build/image-root//var/cache/kiwi/zypper/solv --cache-dir /tmp/machinery-image20150624
-5413-k2qelu/build/image-root//var/cache/kiwi/zypper --config /var/cache/kiwi/zypper/zypper.conf.5428 --no-gpg-checks --root "/tmp/machinery-image20150624-5413-k2qelu/build/
image-root" modifyrepo -p 99 SUSE_Linux_Enterprise_Server_12_x86_64:SLES12-Updates 2>&1]
Jun-24 15:18:06 <1> : EXEC [test -f /tmp/machinery-image20150624-5413-k2qelu/build/image-root//var/cache/kiwi/zypper/repos/SUSE_Linux_Enterprise_Server_12_x86_64:SLES12-Pool
.repo]
Jun-24 15:18:06 <1> : Adding bootstrap zypper service: SUSE_Linux_Enterprise_Server_12_x86_64:SLES12-Pool
Jun-24 15:18:06 <1> : EXEC [/usr/bin/zypper --non-interactive --pkg-cache-dir /var/cache/kiwi/packages --reposd-dir /tmp/machinery-image20150624-5413-k2qelu/build/image-root
//var/cache/kiwi/zypper/repos --solv-cache-dir /tmp/machinery-image20150624-5413-k2qelu/build/image-root//var/cache/kiwi/zypper/solv --cache-dir /tmp/machinery-image20150624
-5413-k2qelu/build/image-root//var/cache/kiwi/zypper --config /var/cache/kiwi/zypper/zypper.conf.5428 --no-gpg-checks --root "/tmp/machinery-image20150624-5413-k2qelu/build/
image-root" addrepo -f --type YUM --keep-packages 'https://updates.suse.com/SUSE/Products/SLE-SERVER/12/x86_64/product?AUTRkVHSnJTjJMEzw7JDFKrgoYUsDd_8iVRGRjNMjQtyRYNNkm1hrm
kfFSzi1LV7ht8G2ZLYJ7JcIaWb0wNDhAfsTUdb4UokRRcqDdi0g0eBvXMWIosjXjKzVOXZ1Bn4BUYtkPRJw2y-?credentials=kiwiRepoCredentials' SUSE_Linux_Enterprise_Server_12_x86_64:SLES12-Pool 2>
&1]
Jun-24 15:18:06 <1> : --> Set priority to: 99
Jun-24 15:18:06 <1> : EXEC [/usr/bin/zypper --non-interactive --pkg-cache-dir /var/cache/kiwi/packages --reposd-dir /tmp/machinery-image20150624-5413-k2qelu/build/image-root
//var/cache/kiwi/zypper/repos --solv-cache-dir /tmp/machinery-image20150624-5413-k2qelu/build/image-root//var/cache/kiwi/zypper/solv --cache-dir /tmp/machinery-image20150624
-5413-k2qelu/build/image-root//var/cache/kiwi/zypper --config /var/cache/kiwi/zypper/zypper.conf.5428 --no-gpg-checks --root "/tmp/machinery-image20150624-5413-k2qelu/build/
image-root" modifyrepo -p 99 SUSE_Linux_Enterprise_Server_12_x86_64:SLES12-Pool 2>&1]
Jun-24 15:18:06 <1> : EXEC [test -f /tmp/machinery-image20150624-5413-k2qelu/build/image-root//var/cache/kiwi/zypper/repos/SLES12-12-0.repo]
Jun-24 15:18:06 <1> : Adding bootstrap zypper service: SLES12-12-0
Jun-24 15:18:06 <1> : EXEC [/usr/bin/zypper --non-interactive --pkg-cache-dir /var/cache/kiwi/packages --reposd-dir /tmp/machinery-image20150624-5413-k2qelu/build/image-root
//var/cache/kiwi/zypper/repos --solv-cache-dir /tmp/machinery-image20150624-5413-k2qelu/build/image-root//var/cache/kiwi/zypper/solv --cache-dir /tmp/machinery-image20150624
-5413-k2qelu/build/image-root//var/cache/kiwi/zypper --config /var/cache/kiwi/zypper/zypper.conf.5428 --no-gpg-checks --root "/tmp/machinery-image20150624-5413-k2qelu/build/
image-root" addrepo -f --type YaST 'nfs://10.160.0.100/dist/install/SLP/SLE-12-Server-GM/x86_64/DVD1' SLES12-12-0 2>&1]
Jun-24 15:18:06 <1> : --> Set priority to: 99
Jun-24 15:18:06 <1> : EXEC [/usr/bin/zypper --non-interactive --pkg-cache-dir /var/cache/kiwi/packages --reposd-dir /tmp/machinery-image20150624-5413-k2qelu/build/image-root
//var/cache/kiwi/zypper/repos --solv-cache-dir /tmp/machinery-image20150624-5413-k2qelu/build/image-root//var/cache/kiwi/zypper/solv --cache-dir /tmp/machinery-image20150624
-5413-k2qelu/build/image-root//var/cache/kiwi/zypper --config /var/cache/kiwi/zypper/zypper.conf.5428 --no-gpg-checks --root "/tmp/machinery-image20150624-5413-k2qelu/build/
image-root" modifyrepo -p 99 SLES12-12-0 2>&1]
Jun-24 15:18:06 <1> : EXEC [test -f /tmp/machinery-image20150624-5413-k2qelu/build/image-root//var/cache/kiwi/zypper/repos/ceph_disk2.repo]
Jun-24 15:18:06 <1> : Adding bootstrap zypper service: ceph_disk2
Jun-24 15:18:06 <1> : EXEC [/usr/bin/zypper --non-interactive --pkg-cache-dir /var/cache/kiwi/packages --reposd-dir /tmp/machinery-image20150624-5413-k2qelu/build/image-root
//var/cache/kiwi/zypper/repos --solv-cache-dir /tmp/machinery-image20150624-5413-k2qelu/build/image-root//var/cache/kiwi/zypper/solv --cache-dir /tmp/machinery-image20150624
-5413-k2qelu/build/image-root//var/cache/kiwi/zypper --config /var/cache/kiwi/zypper/zypper.conf.5428 --no-gpg-checks --root "/tmp/machinery-image20150624-5413-k2qelu/build/
image-root" addrepo -f --type YaST 'iso:///?iso=/home/col/down/SUSE-Enterprise-Storage-1.0-DVD-x86_64-Build0131-Media2.iso' ceph_disk2 2>&1]
Jun-24 15:18:06 <1> : --> Set priority to: 99
Jun-24 15:18:06 <1> : EXEC [/usr/bin/zypper --non-interactive --pkg-cache-dir /var/cache/kiwi/packages --reposd-dir /tmp/machinery-image20150624-5413-k2qelu/build/image-root
//var/cache/kiwi/zypper/repos --solv-cache-dir /tmp/machinery-image20150624-5413-k2qelu/build/image-root//var/cache/kiwi/zypper/solv --cache-dir /tmp/machinery-image20150624
-5413-k2qelu/build/image-root//var/cache/kiwi/zypper --config /var/cache/kiwi/zypper/zypper.conf.5428 --no-gpg-checks --root "/tmp/machinery-image20150624-5413-k2qelu/build/
image-root" modifyrepo -p 99 ceph_disk2 2>&1]
Jun-24 15:18:07 <1> : EXEC [test -f /tmp/machinery-image20150624-5413-k2qelu/build/image-root//var/cache/kiwi/zypper/repos/ceph_disk1.repo]
Jun-24 15:18:07 <1> : Adding bootstrap zypper service: ceph_disk1
Jun-24 15:18:07 <1> : EXEC [/usr/bin/zypper --non-interactive --pkg-cache-dir /var/cache/kiwi/packages --reposd-dir /tmp/machinery-image20150624-5413-k2qelu/build/image-root
//var/cache/kiwi/zypper/repos --solv-cache-dir /tmp/machinery-image20150624-5413-k2qelu/build/image-root//var/cache/kiwi/zypper/solv --cache-dir /tmp/machinery-image20150624
-5413-k2qelu/build/image-root//var/cache/kiwi/zypper --config /var/cache/kiwi/zypper/zypper.conf.5428 --no-gpg-checks --root "/tmp/machinery-image20150624-5413-k2qelu/build/
image-root" addrepo -f --type YaST 'iso:///?iso=/home/col/down/SUSE-Enterprise-Storage-1.0-DVD-x86_64-Build0131-Media1.iso' ceph_disk1 2>&1]
Jun-24 15:18:07 <1> : --> Set priority to: 99
Jun-24 15:18:07 <1> : EXEC [/usr/bin/zypper --non-interactive --pkg-cache-dir /var/cache/kiwi/packages --reposd-dir /tmp/machinery-image20150624-5413-k2qelu/build/image-root
//var/cache/kiwi/zypper/repos --solv-cache-dir /tmp/machinery-image20150624-5413-k2qelu/build/image-root//var/cache/kiwi/zypper/solv --cache-dir /tmp/machinery-image20150624
-5413-k2qelu/build/image-root//var/cache/kiwi/zypper --config /var/cache/kiwi/zypper/zypper.conf.5428 --no-gpg-checks --root "/tmp/machinery-image20150624-5413-k2qelu/build/
image-root" modifyrepo -p 99 ceph_disk1 2>&1]
Jun-24 15:18:07 <1> : EXEC [chmod a+x /dev/shm/lwp-download 2>&1]
Jun-24 15:18:07 <1> : EXEC [/dev/shm/lwp-download https://updates.suse.com/SUSE/Updates/SLE-SERVER/12/x86_64/update/license.tar.gz /tmp/machinery-image20150624-5413-k2qelu/b
uild/image-root//license.tar.gz 2>&1]
Jun-24 15:18:08 <1> : EXEC [chmod a+x /dev/shm/lwp-download 2>&1]
Jun-24 15:18:08 <1> : EXEC [/dev/shm/lwp-download https://updates.suse.com/SUSE/Products/SLE-SERVER/12/x86_64/product/license.tar.gz /tmp/machinery-image20150624-5413-k2qelu
/build/image-root//license.tar.gz 2>&1]
Jun-24 15:18:08 <1> : EXEC [chmod a+x /dev/shm/lwp-download 2>&1]
Jun-24 15:18:08 <1> : EXEC [/dev/shm/lwp-download nfs://10.160.0.100/dist/install/SLP/SLE-12-Server-GM/x86_64/DVD1/license.tar.gz /tmp/machinery-image20150624-5413-k2qelu/bu
ild/image-root//license.tar.gz 2>&1]
Jun-24 15:18:08 <1> : EXEC [chmod a+x /dev/shm/lwp-download 2>&1]
Jun-24 15:18:08 <1> : EXEC [/dev/shm/lwp-download iso:////home/col/down/SUSE-Enterprise-Storage-1.0-DVD-x86_64-Build0131-Media2.iso/license.tar.gz /tmp/machinery-image201506
24-5413-k2qelu/build/image-root//license.tar.gz 2>&1]
Jun-24 15:18:08 <1> : EXEC [chmod a+x /dev/shm/lwp-download 2>&1]
Jun-24 15:18:08 <1> : EXEC [/dev/shm/lwp-download iso:////home/col/down/SUSE-Enterprise-Storage-1.0-DVD-x86_64-Build0131-Media1.iso/license.tar.gz /tmp/machinery-image201506
24-5413-k2qelu/build/image-root//license.tar.gz 2>&1]
Jun-24 15:18:08 <1> : Initializing image system on: /tmp/machinery-image20150624-5413-k2qelu/build/image-root
Jun-24 15:18:08 <1> : EXEC [chmod 755 /tmp/machinery-image20150624-5413-k2qelu/build/image-root/screenrc.smart]
+ export PBL_SKIP_BOOT_TEST=1
+ PBL_SKIP_BOOT_TEST=1
+ trap clean INT TERM
+ export ZYPP_MODALIAS_SYSFS=/tmp
+ ZYPP_MODALIAS_SYSFS=/tmp
+ export YAST_IS_RUNNING=true
+ YAST_IS_RUNNING=true
+ export ZYPP_CONF=/tmp/machinery-image20150624-5413-k2qelu/build/image-root//var/cache/kiwi/zypper/zypp.conf.5428
+ ZYPP_CONF=/tmp/machinery-image20150624-5413-k2qelu/build/image-root//var/cache/kiwi/zypper/zypp.conf.5428
+ export ZYPP_LOCKFILE_ROOT=/tmp/machinery-image20150624-5413-k2qelu/build/image-root
+ ZYPP_LOCKFILE_ROOT=/tmp/machinery-image20150624-5413-k2qelu/build/image-root
+ mkdir -p /tmp/machinery-image20150624-5413-k2qelu/build/image-root/etc/zypp
+ SPID=5602
+ wait 5602
+ /usr/bin/zypper --non-interactive --pkg-cache-dir /var/cache/kiwi/packages --reposd-dir /tmp/machinery-image20150624-5413-k2qelu/build/image-root//var/cache/kiwi/zypper/re
pos --solv-cache-dir /tmp/machinery-image20150624-5413-k2qelu/build/image-root//var/cache/kiwi/zypper/solv --cache-dir /tmp/machinery-image20150624-5413-k2qelu/build/image-r
oot//var/cache/kiwi/zypper --config /var/cache/kiwi/zypper/zypper.conf.5428 --no-gpg-checks --root /tmp/machinery-image20150624-5413-k2qelu/build/image-root install --auto-a
gree-with-licenses --no-recommends FirmwareUpdateKit Mesa Mesa-32bit Mesa-demo-x Mesa-libEGL1 Mesa-libEGL1-32bit Mesa-libGL1 Mesa-libGL1-32bit Mesa-libGLESv2-2 Mesa-libglapi
0 Mesa-libglapi0-32bit MozillaFirefox MozillaFirefox-branding-SLE MozillaFirefox-translations OpenIPMI PackageKit PackageKit-backend-zypp PackageKit-branding-SLE PackageKit-
lang SUSEConnect SuSEfirewall2 aaa_base aaa_base-extras accountsservice accountsservice-lang acl adaptec-firmware adjtimex alsa alsa-plugins alsa-plugins-pulse alsa-utils ap
ache2 apache2-mod_wsgi apache2-prefork apache2-utils apparmor-docs apparmor-parser apparmor-profiles apparmor-utils appres at at-spi2-atk-common at-spi2-atk-gtk2 at-spi2-cor
e atmel-firmware attr audit augeas-lenses autoconf autofs automake autoyast2 autoyast2-installation bash bash-completion bash-doc bc bind-libs bind-libs-32bit bind-utils bin
utils bitmap bitstream-vera-fonts blktrace bluez boost-license1_54_0 branding-SLE brasero brasero-lang brltty btrfsmaintenance btrfsprogs bzip2 ca-certificates ca-certificat
es-mozilla calamari-clients calamari-server cantarell-fonts caribou-common cdrdao cdrkit-cdrtools-compat ceph ceph-common ceph-deploy checkmedia cifs-utils clutter-gtk-lang 
clutter-lang cogl-lang colord-gtk-lang command-not-found convmv coreutils coreutils-lang cpio cpio-lang cpp cpp48 cpupower cracklib cracklib-dict-full crash crash-kmp-defaul
t cron cronie cryptconfig cryptconfig-32bit cryptsetup cups cups-client cups-filters cups-filters-cups-browsed cups-filters-foomatic-rip cups-filters-ghostscript cups-libs c
ups-libs-32bit cups-pk-helper cups-pk-helper-lang curl cyrus-sasl cyrus-sasl-32bit cyrus-sasl-digestmd5 cyrus-sasl-gssapi cyrus-sasl-gssapi-32bit cyrus-sasl-plain cyrus-sasl
-plain-32bit cyrus-sasl-saslauthd db48-utils dbus-1 dbus-1-glib dbus-1-glib-32bit dbus-1-python dbus-1-python3 dbus-1-x11 dconf dconf-lang dejavu-fonts delayacct-utils delta
rpm desktop-data-SLE desktop-file-utils desktop-translations device-mapper device-mapper-32bit dhcp dhcp-client dialog diffutils dirmngr dmidecode dmraid dmz-icon-theme-curs
ors docbook_4 dos2unix dosfstools dracut e2fsprogs ed editres efibootmgr efont-unicode-bitmap-fonts elfutils eog eog-lang espeak ethtool evince evince-lang expat expect fast
jar fd0ssh fdupes file file-magic file-roller file-roller-lang filesystem fillup findutils finger fipscheck fontconfig fontconfig-32bit fonts-config fonttosfnt fping freetyp
e fribidi fribidi-32bit ft2demos fuse gamin-server gawk gconf-editor gconf-editor-lang gconf2 gconf2-branding-SLES gconf2-lang gcr-data gcr-lang gcr-prompter gd gdb gdk-pixb
uf-lang gdk-pixbuf-loader-rsvg gdk-pixbuf-query-loaders gdm gdm-branding-upstream gdm-lang gdmflexiserver gedit gedit-lang genisoimage gettext-runtime gettext-runtime-32bit 
ghostscript ghostscript-fonts-other ghostscript-fonts-std ghostscript-x11 gio-branding-SLE girepository-1_0 glib-networking glib-networking-lang glib2-lang glib2-tools glibc
 glibc-32bit glibc-i18ndata glibc-locale glibc-locale-32bit gnome-bluetooth gnome-bluetooth-lang gnome-control-center gnome-control-center-lang gnome-desktop-lang gnome-icon
-theme gnome-icon-theme-symbolic gnome-keyring gnome-keyring-lang gnome-keyring-pam gnome-keyring-pam-32bit gnome-menus gnome-menus-branding-SLE gnome-menus-lang gnome-mime-
data gnome-nettool gnome-nettool-lang gnome-packagekit gnome-packagekit-lang gnome-power-manager gnome-power-manager-lang gnome-pty-helper gnome-session gnome-session-core g
nome-session-default-session gnome-session-lang gnome-settings-daemon gnome-settings-daemon-lang gnome-shell gnome-shell-browser-plugin gnome-shell-classic gnome-shell-exten
sions-common gnome-shell-extensions-common-lang gnome-shell-lang gnome-shell-search-provider-nautilus gnome-system-monitor gnome-system-monitor-lang gnome-terminal gnome-ter
minal-lang gnome-themes-accessibility gnome-tweak-tool gnome-tweak-tool-lang gnome-user-docs gnome-user-docs-lang gnome-version gnu-unifont-bitmap-fonts google-opensans-font
s gpart gperftools gpg2 gpg2-lang gpm gpm-32bit gptfdisk graphite-web grep groff groff-full grub2 grub2-branding-SLE grub2-i386-pc grub2-snapper-plugin gsettings-backend-dco
nf gsettings-desktop-schemas gsettings-desktop-schemas-lang gstreamer gstreamer-lang gstreamer-plugins-bad gstreamer-plugins-bad-lang gstreamer-plugins-base gstreamer-plugin
s-base-lang gstreamer-plugins-good gstreamer-plugins-good-lang gtk2-branding-SLED gtk2-engine-hcengine gtk2-lang gtk2-metatheme-adwaita gtk2-theming-engine-adwaita gtk2-tool
s gtk3-data gtk3-lang gtk3-metatheme-adwaita gtk3-theming-engine-adwaita gtk3-tools gucharmap gucharmap-lang gvfs gvfs-backends gvfs-fuse gvfs-lang gxditview gzip hardlink h
aveged hdparm hicolor-icon-theme hunspell hunspell-tools hwinfo iceauth icedax icewm icewm-lite icewm-theme-branding icmpinfo info info2html initviocons input-utils insserv-
compat inst-source-utils intlfonts intlfonts-euro-bitmap-fonts ipmitool iproute2 iptables iputils ipw-firmware irqbalance iscsiuio iso-codes iso-codes-lang iso_ent joe json-
glib-lang kbd kdump kernel-default kernel-firmware kexec-tools keyutils kmod kmod-compat kpartx krb5 krb5-32bit latex2html-pngicons less libFLAC8 libGLU1 libHX28 libHX28-32b
it libICE6 libICE6-32bit libLLVM libLLVM-32bit libQt5Core5 libQt5DBus5 libQt5Gui5 libQt5Widgets5 libQt5X11Extras5 libSDL-1_2-0 libSM6 libSM6-32bit libSoundTouch0 libX11-6 li
bX11-6-32bit libX11-data libX11-xcb1 libX11-xcb1-32bit libXRes1 libXau6 libXau6-32bit libXaw3d8 libXaw7 libXcomposite1 libXcursor1 libXcursor1-32bit libXdamage1 libXdamage1-
32bit libXdmcp6 libXevie1 libXext6 libXext6-32bit libXfixes3 libXfixes3-32bit libXfont1 libXfontcache1 libXft2 libXft2-32bit libXi6 libXi6-32bit libXinerama1 libXinerama1-32
bit libXmu6 libXmuu1 libXpm4 libXrandr2 libXrandr2-32bit libXrender1 libXrender1-32bit libXss1 libXss1-32bit libXt6 libXtst6 libXv1 libXxf86dga1 libXxf86misc1 libXxf86vm1 li
bXxf86vm1-32bit libaccountsservice0 libacl1 libacl1-32bit libadns1 libaio1 libao-plugins4 libao4 libapparmor1 libapr-util1 libapr1 libarchive13 libasm1 libasound2 libasound2
-32bit libaspell15 libass5 libassuan0 libatasmart4 libatk-1_0-0 libatk-1_0-0-32bit libatk-bridge-2_0-0 libatkmm-1_6-1 libatspi0 libattr1 libattr1-32bit libaudiofile1 libaudi
t1 libaudit1-32bit libaugeas0 libauparse0 libavahi-client3 libavahi-client3-32bit libavahi-common3 libavahi-common3-32bit libavahi-glib1 libbasicobjects0 libblkid1 libblkid1
-32bit libbluetooth3 libbluray1 libboost_program_options1_54_0 libboost_regex1_54_0 libboost_system1_54_0 libboost_thread1_54_0 libbrasero-burn3-1 libbrasero-media3-1 libbra
sero-utils3-1 libbrlapi0_6 libbtrfs0 libburn4 libbz2-1 libbz2-1-32bit libcairo-gobject2 libcairo2 libcairo2-32bit libcairomm-1_0-1 libcamgm100 libcanberra-gtk3-0 libcanberra
0 libcap-ng0 libcap2 libcap2-32bit libcares2 libcaribou0 libcdda_interface0 libcdda_paranoia0 libcdio14 libcdio_cdda1 libcdio_paranoia1 libcelt0-2 libcephfs1 libcheese-commo
n libcheese-gtk23 libcheese7 libcloog-isl4 libclutter-1_0-0 libclutter-gst-2_0-0 libclutter-gtk-1_0-0 libcogl-pango15 libcogl15 libcollection2 libcolord-gtk1 libcolord2 libc
om_err2 libcom_err2-32bit libcpupower0 libcrack2 libcrack2-32bit libcroco-0_6-3 libcroco-0_6-3-32bit libcryptmount0 libcryptmount0-32bit libcryptsetup4 libcryptsetup4-32bit 
libcurl4 libcurl4-32bit libdb-4_8 libdb-4_8-32bit libdbus-1-3 libdbus-1-3-32bit libdcerpc-binding0 libdcerpc-binding0-32bit libdcerpc0 libdcerpc0-32bit libdconf1 libdhash1 l
ibdialog11 libdjvulibre21 libdm0 libdmx1 libdotconf0 libdrm2 libdrm2-32bit libdrm_intel1 libdrm_intel1-32bit libdrm_nouveau2 libdrm_nouveau2-32bit libdrm_radeon1 libdrm_rade
on1-32bit libdv4 libdvdnav4 libdvdread4 libdw1 libedit0 libelf0 libelf1 libelf1-32bit libenca0 libenchant1 libesd0 libesmtp libestr0 libevdev2 libevdocument3-4 libevent-2_0-
5 libevview3-3 libexempi3 libexif12 libexpat1 libexpat1-32bit libext2fs2 libfam0-gamin libffi4 libffi4-32bit libfftw3-3 libfipscheck1 libfipscheck1-32bit libfltk1 libfontenc
1 libfreebl3 libfreebl3-32bit libfreetype6 libfreetype6-32bit libftgl2 libfuse2 libgbm1 libgbm1-32bit libgc1 libgcc_s1 libgcc_s1-32bit libgck-1-0 libgck-modules-gnome-keyrin
g libgcr-3-1 libgcrypt20 libgcrypt20-32bit libgdbm4 libgdbm4-32bit libgdk_pixbuf-2_0-0 libgdm1 libgee-0_8-2 libgensec0 libgensec0-32bit libgeoclue0 libgeocode-glib0 libgif6-
32bit libgio-2_0-0 libgio-2_0-0-32bit libgiomm-2_4-1 libgirepository-1_0-1 libgjs0 libglade-2_0-0 libglib-2_0-0 libglib-2_0-0-32bit libglibmm-2_4-1 libgme0 libgmime-2_6-0 li
bgmodule-2_0-0 libgmodule-2_0-0-32bit libgmp10 libgnome-bluetooth12 libgnome-desktop-3-8 libgnome-desktop-3_0-common libgnome-keyring-lang libgnome-keyring0 libgnome-menu-3-
0 libgnomesu libgnomesu-lang libgnomesu0 libgnutls28 libgoa-1_0-0 libgoa-backend-1_0-1 libgobject-2_0-0 libgobject-2_0-0-32bit libgpg-error0 libgpg-error0-32bit libgpgme11 l
ibgphoto2-6 libgphoto2-6-lang libgraphite2-3 libgraphite2-3-32bit libgsm1 libgssglue1 libgstallocators-1_0-0 libgstapp-1_0-0 libgstaudio-1_0-0 libgstbasecamerabinsrc-1_0-0 l
ibgstcodecparsers-1_0-0 libgstegl-1_0-0 libgstfft-1_0-0 libgstmpegts-1_0-0 libgstpbutils-1_0-0 libgstphotography-1_0-0 libgstreamer-1_0-0 libgstriff-1_0-0 libgstrtp-1_0-0 li
bgstrtsp-1_0-0 libgstsdp-1_0-0 libgsttag-1_0-0 libgstvideo-1_0-0 libgthread-2_0-0 libgtk-2_0-0 libgtk-3-0 libgtkmm-3_0-1 libgtksourceview-3_0-1 libgtop-2_0-10 libgtop-lang l
ibgucharmap_2_90-7 libgudev-1_0-0 libgvfscommon0 libgweather-3-6 libgweather-data libgweather-lang libgxps2 libharfbuzz-icu0 libharfbuzz0 libharfbuzz0-32bit libhavege1 libho
gweed2 libibus-1_0-5 libical1 libicu52_1 libicu52_1-data libidn-tools libidn11 libidn11-32bit libimobiledevice4 libini_config3 libiptc0 libisl10 libisofs6 libiw30 libjack0 l
ibjasper1 libjavascriptcoregtk-3_0-0 libjbig2 libjbig2-32bit libjpeg8 libjpeg8-32bit libjson-c2 libjson-glib-1_0-0 libkate1 libkeyutils1 libkeyutils1-32bit libkmod2 libkpath
sea6 libksba8 liblcms1 liblcms1-32bit liblcms2-2 libldap-2_4-2 libldap-2_4-2-32bit libldapcpp1 libldb1 libldb1-32bit libleveldb1 liblockdev1 liblogging0 liblouis2 liblrdf2 l
ibltdl7 liblua5_1 liblua5_1-32bit liblua5_2 liblzma5 liblzma5-32bit liblzo2-2 libmagic1 libmagic1-32bit libmjpegutils-2_0-0 libmm-glib0 libmms0 libmng1 libmng1-32bit libmnl0
 libmodman1 libmodplug1 libmount1 libmount1-32bit libmozjs-17_0 libmpc3 libmpfr4 libmtdev1 libmtp9 libmutter0 libmysqlclient18 libnautilus-extension1 libncurses5 libncurses5
-32bit libncurses6 libndr-krb5pac0 libndr-krb5pac0-32bit libndr-nbt0 libndr-nbt0-32bit libndr-standard0 libndr-standard0-32bit libndr0 libndr0-32bit libneon27 libnetapi0 lib
netapi0-32bit libnetfilter_conntrack3 libnetpbm11 libnettle4 libnfnetlink0 libnl-config libnl1 libnl3-200 libnm-glib-vpn1 libnm-glib4 libnm-gtk0 libnm-util2 libnotify4 libns
cd1 libnscd1-32bit libnsssharedhelper0 libnuma1 libofa0 libogg0 liboggkate1 libopenct1 libopenssl1_0_0 libopenssl1_0_0-32bit libopus0 liborc-0_4-0 libp11-kit0 libpackagekit-
glib2-16 libpango-1_0-0 libpango-1_0-0-32bit libpangomm-1_4-1 libparted0 libpath_utils1 libpcap1 libpci3 libpci3-32bit libpciaccess0 libpciaccess0-32bit libpcre1 libpcre1-32
bit libpcre16-0 libpdb0 libpdb0-32bit libpeas-1_0-0 libpeas-gtk-1_0-0 libpipeline1 libpixman-1-0 libpixman-1-0-32bit libplist1 libply-boot-client2 libply-splash-core2 libply
-splash-graphics2 libply2 libpng16-16 libpng16-16-32bit libpolkit0 libpoppler-glib8 libpoppler44 libpopt0 libpopt0-32bit libportaudio2 libpq5 libprocps3 libproxy1 libproxy1-
config-gnome3 libpth20 libpulse-mainloop-glib0 libpulse0 libpwquality-lang libpwquality1 libpyglib-gi-2_0-python2-0 libpyglib-gi-2_0-python3-0 libpython2_7-1_0 libpython2_7-
1_0-32bit libpython3_4m1_0 libqpdf13 libqrencode3 libqt4 libqt4-32bit libqt4-sql libqt4-sql-32bit libqt4-sql-mysql libqt4-x11 libqt4-x11-32bit libquicktime0 libquvi libquvi-
scripts librados2 libraptor2-0 librbd1 libreadline6 libref_array1 libregistry0 libreiserfscore0 librest0 librpcsecgss3 librsvg-2-2 libruby2_1-2_1 libsamba-credentials0 libsa
mba-credentials0-32bit libsamba-hostconfig0 libsamba-hostconfig0-32bit libsamba-util0 libsamba-util0-32bit libsamdb0 libsamdb0-32bit libsamplerate0 libsasl2-3 libsasl2-3-32b
it libschroedinger-1_0-0 libseccomp2 libsecret-1-0 libsecret-lang libselinux1 libselinux1-32bit libsemanage1 libsemanage1-32bit libsensors4 libsepol1 libsepol1-32bit libsgut
ils2-2 libsigc-2_0-0 libslang2 libsmartcols1 libsmbclient-raw0 libsmbclient-raw0-32bit libsmbclient0 libsmbconf0 libsmbconf0-32bit libsmbldap0 libsmbldap0-32bit libsmi libsm
i2 libsnapper2 libsnappy1 libsndfile1 libsnmp30 libsoftokn3 libsoftokn3-32bit libsolv-tools libsoup-2_4-1 libsoup-lang libspandsp2 libspectre1 libspeechd2 libspeex1 libspeex
dsp1 libsqlite3-0 libsqlite3-0-32bit libssh2-1 libssh2-1-32bit libsss_idmap0 libstartup-notification-1-0 libstdc++6 libstdc++6-32bit libstorage-ruby libstorage5 libstroke li
btag1 libtalloc2 libtalloc2-32bit libtasn1 libtasn1-6 libtdb1 libtdb1-32bit libtelepathy-glib0 libtelepathy-logger3 libtevent-util0 libtevent-util0-32bit libtevent0 libteven
t0-32bit libtheora0 libtiff5 libtiff5-32bit libtirpc1 libtool libtool-32bit libtotem-plparser18 libtracker-common-0_16-0 libtracker-sparql-0_16-0 libttf2 libudev1 libudev1-3
2bit libudisks2-0 libunwind libunwind-devel libupower-glib3 libusb-0_1-4 libusb-1_0-0 libusbmuxd2 libustr-1_0-1 libustr-1_0-1-32bit libutempter0 libuuid1 libuuid1-32bit libv
4l libv4l1-0 libv4l2-0 libv4lconvert0 libvdpau1 libvisual libvorbis0 libvorbisenc2 libvorbisfile3 libvpx1 libvte2_90-9 libwacom-data libwacom2 libwavpack1 libwbclient0 libwb
client0-32bit libwebkitgtk-3_0-0 libwebkitgtk3-lang libwebp5 libwebpmux1 libwebrtc_audio_processing0 libwicked-0-6 libwnck-3-0 libwnck-lang libwrap0 libwrap0-32bit libx86emu
1 libxcb-dri2-0 libxcb-dri2-0-32bit libxcb-glx0 libxcb-glx0-32bit libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-render0 libxcb-render0
-32bit libxcb-shape0 libxcb-shm0 libxcb-shm0-32bit libxcb-sync1 libxcb-util1 libxcb-xfixes0 libxcb-xfixes0-32bit libxcb-xkb1 libxcb-xv0 libxcb1 libxcb1-32bit libxkbcommon-x1
1-0 libxkbcommon0 libxkbfile1 libxklavier16 libxml2-2 libxml2-2-32bit libxml2-tools libxshmfence1 libxslt-tools libxslt1 libxtables10 libyaml-0-2 libyelp0 libyui-ncurses-pkg
6 libyui-ncurses6 libyui-qt-pkg6 libyui-qt6 libyui6 libz1 libz1-32bit libzio1 libzmq3 libzypp listres lockdev logrotate lsb-release lsof lsscsi lua luasocket luit lvm2 m4 ma
ilx make makedumpfile man man-pages man-pages-posix master-boot-code mc mc-lang mcelog mdadm metamail metatheme-adwaita-common mingetty mkfontdir mkfontscale mksh mlocate mo
zilla-nspr mozilla-nspr-32bit mozilla-nss mozilla-nss-32bit mozilla-nss-certs mozilla-nss-certs-32bit mpt-firmware mtools multipath-tools mutt mutter mutter-data mutter-lang
 nano nautilus nautilus-file-roller nautilus-lang nautilus-open-terminal nautilus-open-terminal-lang nautilus-share nautilus-share-lang ncurses-utils net-snmp net-tools netc
at-openbsd netcfg netpbm nfs-client nfs-doc nfs-kernel-server nfsidmap notification-daemon notification-daemon-lang novell-sound-theme nscd ntp numactl ofl open-iscsi openct
 openldap2-client opensc openslp openslp-32bit openslp-server openssh openssh-askpass openssh-helpers openssl opie opie-32bit orca orca-lang os-prober p11-kit p11-kit-tools 
p7zip pam pam-32bit pam-config pam-doc pam-modules pam-modules-32bit pam_mount pam_mount-32bit pango-modules pango-modules-32bit parted patch patterns-sle-gnome-basic patter
ns-sles-32bit patterns-sles-Minimal patterns-sles-Minimal-32bit patterns-sles-apparmor patterns-sles-apparmor-32bit patterns-sles-base patterns-sles-base-32bit patterns-sles
-documentation patterns-sles-documentation-32bit patterns-sles-x11 patterns-sles-x11-32bit pax pciutils pciutils-ids pcsc-lite perl perl-32bit perl-Bit-Vector perl-Bootloade
r perl-Bootloader-YAML perl-Carp-Clan perl-Config-Crontab perl-Config-IniFiles perl-Crypt-SmbHash perl-DBD-SQLite perl-DBI perl-Date-Calc perl-Digest-HMAC perl-Digest-MD4 pe
rl-Digest-SHA1 perl-Encode-Locale perl-File-Listing perl-HTML-Parser perl-HTML-Tagset perl-HTTP-Cookies perl-HTTP-Daemon perl-HTTP-Date perl-HTTP-Message perl-HTTP-Negotiate
 perl-IO-HTML perl-IO-Socket-SSL perl-LWP-MediaTypes perl-LWP-Protocol-https perl-List-MoreUtils perl-Net-DBus perl-Net-DNS perl-Net-Daemon perl-Net-HTTP perl-Net-SSLeay per
l-Parse-RecDescent perl-PlRPC perl-RPC-XML perl-SNMP perl-Sub-Uplevel perl-Term-ReadKey perl-Test-Exception perl-Tie-IxHash perl-TimeDate perl-URI perl-WWW-RobotRules perl-X
11-Protocol perl-X500-DN perl-XML-LibXML perl-XML-NamespaceSupport perl-XML-Parser perl-XML-SAX perl-XML-SAX-Base perl-XML-SAX-Expat perl-XML-Simple perl-XML-Twig perl-XML-W
riter perl-XML-XPath perl-XML-XPathEngine perl-YAML-LibYAML perl-apparmor perl-base perl-camgm perl-gettext perl-libwww-perl permissions pigz pinentry pkg-config plymouth pl
ymouth-branding-SLE plymouth-dracut plymouth-plugin-label plymouth-plugin-script plymouth-scripts polkit polkit-default-privs polkit-gnome polkit-gnome-lang poppler-data pop
pler-tools postfix postgresql-init postgresql93 postgresql93-server ppp pptp prctl procinfo procmail procps psmisc psmisc-lang psutils pulseaudio pulseaudio-esound-compat pu
lseaudio-lang pulseaudio-module-x11 pulseaudio-utils pytalloc pytalloc-32bit python python-Django python-Flask python-Jinja2 python-M2Crypto python-Mako python-MarkupSafe py
thon-Pillow python-PyYAML python-SQLAlchemy python-Twisted python-Werkzeug python-alembic python-apache-libcloud python-argparse python-base python-cairo python-carbon pytho
n-ceph python-cffi python-cryptography python-cups python-cupshelpers python-dateutil python-django-tagging python-djangorestframework python-ecdsa python-execnet python-gev
ent python-gobject python-gobject-cairo python-greenlet python-itsdangerous python-lxml python-msgpack-python python-pam python-paramiko python-psutil python-psycogreen pyth
on-psycopg2 python-pushy python-pyOpenSSL python-pycparser python-pycrypto python-pycurl python-pyparsing python-pyserial python-pytz python-pyzmq python-remoto python-reque
sts python-setuptools python-simplejson python-six python-smbc python-solv python-whisper python-xml python-zerorpc python-zope.interface python3 python3-atspi python3-base 
python3-brlapi python3-cairo python3-gedit python3-gobject python3-louis python3-speechd quota readline-doc recode reiserfs release-notes-sles rendercheck rgb rpcbind rpm rp
m-32bit rpm-python rsh rsync rsyslog rtkit ruby ruby-common ruby2.1 ruby2.1-rubygem-fast_gettext ruby2.1-rubygem-gem2rpm ruby2.1-rubygem-ruby-dbus ruby2.1-rubygem-suse-conne
ct ruby2.1-stdlib salt salt-master salt-minion samba samba-32bit samba-client samba-client-32bit samba-libs samba-libs-32bit scout screen sed sed-lang sessreg setxkbmap sg3_
utils sgml-skel shadow shared-mime-info sharutils sharutils-lang sles-admin_en-pdf sles-deployment_en-pdf sles-installquick_en-pdf sles-manuals_en sles-release sles-security
_en-pdf sles-storage_en-pdf sles-tuning_en-pdf smartmontools snapper snapper-zypp-plugin snmp-mibs sound-theme-freedesktop speech-dispatcher speech-dispatcher-module-espeak 
sqlite3 sssd sssd-32bit sssd-krb5-common sssd-ldap star strace strace-32bit sudo supportutils suse-build-key suse-module-tools susehelp susehelp_en sysconfig sysconfig-netco
nfig sysfsutils sysfsutils-32bit syslinux syslog-service system-config-printer-common system-config-printer-common-lang system-config-printer-dbus-service systemd systemd-32
bit systemd-bash-completion systemd-presets-branding-SLE systemd-sysvinit sysvinit-tools tar tar-lang tcl tcl-32bit tcpd tcpdump tcsh telnet terminfo terminfo-base tigervnc 
time timezone tk tk-32bit totem-pl-parser totem-pl-parser-lang traceroute typelib-1_0-AccountsService-1_0 typelib-1_0-Atk-1_0 typelib-1_0-Atspi-2_0 typelib-1_0-Caribou-1_0 t
ypelib-1_0-Clutter-1_0 typelib-1_0-Cogl-1_0 typelib-1_0-CoglPango-1_0 typelib-1_0-GMenu-3_0 typelib-1_0-Gck-1 typelib-1_0-Gcr-3 typelib-1_0-GdkPixbuf-2_0 typelib-1_0-Gdm-1_0
 typelib-1_0-GjsPrivate-1_0 typelib-1_0-GnomeBluetooth-1_0 typelib-1_0-GnomeDesktop-3_0 typelib-1_0-GnomeKeyring-1_0 typelib-1_0-Gtk-3_0 typelib-1_0-GtkSource-3_0 typelib-1_
0-IBus-1_0 typelib-1_0-Json-1_0 typelib-1_0-Meta-3_0 typelib-1_0-NMClient-1_0 typelib-1_0-NMGtk-1_0 typelib-1_0-NetworkManager-1_0 typelib-1_0-Notify-0_7 typelib-1_0-Package
KitGlib-1_0 typelib-1_0-Pango-1_0 typelib-1_0-Peas-1_0 typelib-1_0-PeasGtk-1_0 typelib-1_0-Polkit-1_0 typelib-1_0-Soup-2_4 typelib-1_0-TelepathyGlib-0_12 typelib-1_0-Telepat
hyLogger-0_2 typelib-1_0-UpowerGlib-1_0 typelib-1_0-Wnck-3_0 ucode-intel udev udev-configure-printer udisks2 udisks2-lang unclutter unrar unzip update-alternatives upower up
ower-lang usbmuxd usbutils util-linux util-linux-lang util-linux-systemd viewres vim vim-data vino vino-lang vlan vlock vorbis-tools vorbis-tools-lang vsftpd vte-lang w3m wa
llpaper-branding-SLE wget which wicked wicked-service wireless-tools wodim x11-tools x11perf x86info xauth xbacklight xbitmaps xclock xconsole xcursor-themes xcursorgen xdg-
menu xdg-user-dirs xdg-user-dirs-gtk xdg-user-dirs-gtk-lang xdg-user-dirs-lang xdg-utils xdm xdmbgrd xdpyinfo xev xeyes xf86-input-evdev xf86-input-synaptics xf86-input-vmmo
use xf86-input-void xf86-input-wacom xf86-video-fbdev xf86-video-mga xf86-video-modesetting xf86-video-vesa xfd xfontsel xfsprogs xgamma xhost xinetd xinit xinput xkbcomp xk
bevd xkbprint xkbutils xkeyboard-config xkeyboard-config-lang xkill xlockmore xlogo xlsatoms xlsclients xlsfonts xmag xmessage xmodmap xorg-x11 xorg-x11-Xvnc xorg-x11-driver
-video xorg-x11-essentials xorg-x11-fonts xorg-x11-fonts-core xorg-x11-libs xorg-x11-server xorg-x11-server-extra xprop xrandr xrdb xrestop xscope xscreensaver xscreensaver-
data xset xsetmode xsetpointer xsetroot xtables-plugins xterm xtermset xvinfo xwd xwininfo xz xz-lang yast2 yast2-add-on yast2-apparmor yast2-audit-laf yast2-auth-client yas
t2-auth-server yast2-boot-server yast2-bootloader yast2-branding-SLE yast2-ca-management yast2-control-center yast2-control-center-gnome yast2-core yast2-country yast2-count
ry-data yast2-dhcp-server yast2-dns-server yast2-firewall yast2-ftp-server yast2-hardware-detection yast2-http-server yast2-inetd yast2-installation yast2-instserver yast2-i
scsi-client yast2-isns yast2-kdump yast2-ldap yast2-mail yast2-metapackage-handler yast2-network yast2-nfs-client yast2-nfs-common yast2-nfs-server yast2-nis-client yast2-ni
s-server yast2-ntp-client yast2-online-update yast2-online-update-frontend yast2-packager yast2-pam yast2-perl-bindings yast2-pkg-bindings yast2-printer yast2-proxy yast2-re
gistration yast2-ruby-bindings yast2-samba-client yast2-samba-server yast2-schema yast2-security yast2-services-manager yast2-slp yast2-snapper yast2-sound yast2-squid yast2
-storage yast2-sudo yast2-support yast2-sysconfig yast2-tftp-server yast2-theme-SLE yast2-trans-en_US yast2-trans-stats yast2-transfer yast2-update yast2-users yast2-vm yast
2-x11 yast2-xml yast2-ycp-ui-bindings yelp yelp-lang yelp-xsl yp-tools ypbind zenity zenity-lang zip zisofs-tools zsh zypp-plugin-python zypper zypper-log zypper
Specified path '/home/col/down' is not a directory: dir:///home/col/down

Abort, retry, ignore? [a/r/i/? shows all options] (a): a
Reposit+ /usr/bin/zypper --non-interactive --pkg-cache-dir /var/cache/kiwi/packages --reposd-dir /tmp/machinery-image20150624-5413-k2qelu/build/image-root//var/cache/kiwi/zypper/repos --solv-cache-dir /tmp/machinery-image20150624-5413-k2qelu/build/image-root//var/cache/kiwi/zypper/solv --cache-dir /tmp/machinery-image20150624-5413-k2qelu/build/image-root//var/cache/kiwi/zypper --config /var/cache/kiwi/zypper/zypper.conf.5428 --no-gpg-checks --root /tmp/machinery-image20150624-5413-k2qelu/build/image-root install --auto-agree-with-licenses --no-recommends FirmwareUpdateKit Mesa Mesa-32bit Mesa-demo-x Mesa-libEGL1 Mesa-libEGL1-32bit Mesa-libGL1 Mesa-libGL1-32bit Mesa-libGLESv2-2 Mesa-libglapi0 Mesa-libglapi0-32bit MozillaFirefox MozillaFirefox-branding-SLE MozillaFirefox-translations OpenIPMI PackageKit PackageKit-backend-zypp PackageKit-branding-SLE PackageKit-lang SUSEConnect SuSEfirewall2 aaa_base aaa_base-extras accountsservice accountsservice-lang acl adaptec-firmware adjtimex alsa alsa-plugins alsa-plugins-pulse alsa-utils apache2 apache2-mod_wsgi apache2-prefork apache2-utils apparmor-docs apparmor-parser apparmor-profiles apparmor-utils appres at at-spi2-atk-common at-spi2-atk-gtk2 at-spi2-core atmel-firmware attr audit augeas-lenses autoconf autofs automake autoyast2 autoyast2-installation bash bash-completion bash-doc bc bind-libs bind-libs-32bit bind-utils binutils bitmap bitstream-vera-fonts blktrace bluez boost-license1_54_0 branding-SLE brasero brasero-lang brltty btrfsmaintenance btrfsprogs bzip2 ca-certificates ca-certificates-mozilla calamari-clients calamari-server cantarell-fonts caribou-common cdrdao cdrkit-cdrtools-compat ceph ceph-common ceph-deploy checkmedia cifs-utils clutter-gtk-lang clutter-lang cogl-lang colord-gtk-lang command-not-found convmv coreutils coreutils-lang cpio cpio-lang cpp cpp48 cpupower cracklib cracklib-dict-full crash crash-kmp-default cron cronie cryptconfig cryptconfig-32bit cryptsetup cups cups-client cups-filters cups-filters-cups-browsed cups-filters-foomatic-rip cups-filters-ghostscript cups-libs cups-libs-32bit cups-pk-helper cups-pk-helper-lang curl cyrus-sasl cyrus-sasl-32bit cyrus-sasl-digestmd5 cyrus-sasl-gssapi cyrus-sasl-gssapi-32bit cyrus-sasl-plain cyrus-sasl-plain-32bit cyrus-sasl-saslauthd db48-utils dbus-1 dbus-1-glib dbus-1-glib-32bit dbus-1-python dbus-1-python3 dbus-1-x11 dconf dconf-lang dejavu-fonts delayacct-utils deltarpm desktop-data-SLE desktop-file-utils desktop-translations device-mapper device-mapper-32bit dhcp dhcp-client dialog diffutils dirmngr dmidecode dmraid dmz-icon-theme-cursors docbook_4 dos2unix dosfstools dracut e2fsprogs ed editres efibootmgr efont-unicode-bitmap-fonts elfutils eog eog-lang espeak ethtool evince evince-lang expat expect fastjar fd0ssh fdupes file file-magic file-roller file-roller-lang filesystem fillup findutils finger fipscheck fontconfig fontconfig-32bit fonts-config fonttosfnt fping freetype fribidi fribidi-32bit ft2demos fuse gamin-server gawk gconf-editor gconf-editor-lang gconf2 gconf2-branding-SLES gconf2-lang gcr-data gcr-lang gcr-prompter gd gdb gdk-pixbuf-lang gdk-pixbuf-loader-rsvg gdk-pixbuf-query-loaders gdm gdm-branding-upstream gdm-lang gdmflexiserver gedit gedit-lang genisoimage gettext-runtime gettext-runtime-32bit ghostscript ghostscript-fonts-other ghostscript-fonts-std ghostscript-x11 gio-branding-SLE girepository-1_0 glib-networking glib-networking-lang glib2-lang glib2-tools glibc glibc-32bit glibc-i18ndata glibc-locale glibc-locale-32bit gnome-bluetooth gnome-bluetooth-lang gnome-control-center gnome-control-center-lang gnome-desktop-lang gnome-icon-theme gnome-icon-theme-symbolic gnome-keyring gnome-keyring-lang gnome-keyring-pam gnome-keyring-pam-32bit gnome-menus gnome-menus-branding-SLE gnome-menus-lang gnome-mime-data gnome-nettool gnome-nettool-lang gnome-packagekit gnome-packagekit-lang gnome-power-manager gnome-power-manager-lang gnome-pty-helper gnome-session gnome-session-core gnome-session-default-session gnome-session-lang gnome-settings-daemon gnome-settings-daemon-lang gnome-shell gnome-shell-browser-plugin gnome-shell-classic gnome-shell-extensions-common gnome-shell-extensions-common-lang gnome-shell-lang gnome-shell-search-provider-nautilus gnome-system-monitor gnome-system-monitor-lang gnome-terminal gnome-terminal-lang gnome-themes-accessibility gnome-tweak-tool gnome-tweak-tool-lang gnome-user-docs gnome-user-docs-lang gnome-version gnu-unifont-bitmap-fonts google-opensans-fonts gpart gperftools gpg2 gpg2-lang gpm gpm-32bit gptfdisk graphite-web grep groff groff-full grub2 grub2-branding-SLE grub2-i386-pc grub2-snapper-plugin gsettings-backend-dconf gsettings-desktop-schemas gsettings-desktop-schemas-lang gstreamer gstreamer-lang gstreamer-plugins-bad gstreamer-plugins-bad-lang gstreamer-plugins-base gstreamer-plugins-base-lang gstreamer-plugins-good gstreamer-plugins-good-lang gtk2-branding-SLED gtk2-engine-hcengine gtk2-lang gtk2-metatheme-adwaita gtk2-theming-engine-adwaita gtk2-tools gtk3-data gtk3-lang gtk3-metatheme-adwaita gtk3-theming-engine-adwaita gtk3-tools gucharmap gucharmap-lang gvfs gvfs-backends gvfs-fuse gvfs-lang gxditview gzip hardlink haveged hdparm hicolor-icon-theme hunspell hunspell-tools hwinfo iceauth icedax icewm icewm-lite icewm-theme-branding icmpinfo info info2html initviocons input-utils insserv-compat inst-source-utils intlfonts intlfonts-euro-bitmap-fonts ipmitool iproute2 iptables iputils ipw-firmware irqbalance iscsiuio iso-codes iso-codes-lang iso_ent joe json-glib-lang kbd kdump kernel-default kernel-firmware kexec-tools keyutils kmod kmod-compat kpartx krb5 krb5-32bit latex2html-pngicons less libFLAC8 libGLU1 libHX28 libHX28-32bit libICE6 libICE6-32bit libLLVM libLLVM-32bit libQt5Core5 libQt5DBus5 libQt5Gui5 libQt5Widgets5 libQt5X11Extras5 libSDL-1_2-0 libSM6 libSM6-32bit libSoundTouch0 libX11-6 libX11-6-32bit libX11-data libX11-xcb1 libX11-xcb1-32bit libXRes1 libXau6 libXau6-32bit libXaw3d8 libXaw7 libXcomposite1 libXcursor1 libXcursor1-32bit libXdamage1 libXdamage1-32bit libXdmcp6 libXevie1 libXext6 libXext6-32bit libXfixes3 libXfixes3-32bit libXfont1 libXfontcache1 libXft2 libXft2-32bit libXi6 libXi6-32bit libXinerama1 libXinerama1-32bit libXmu6 libXmuu1 libXpm4 libXrandr2 libXrandr2-32bit libXrender1 libXrender1-32bit libXss1 libXss1-32bit libXt6 libXtst6 libXv1 libXxf86dga1 libXxf86misc1 libXxf86vm1 libXxf86vm1-32bit libaccountsservice0 libacl1 libacl1-32bit libadns1 libaio1 libao-plugins4 libao4 libapparmor1 libapr-util1 libapr1 libarchive13 libasm1 libasound2 libasound2-32bit libaspell15 libass5 libassuan0 libatasmart4 libatk-1_0-0 libatk-1_0-0-32bit libatk-bridge-2_0-0 libatkmm-1_6-1 libatspi0 libattr1 libattr1-32bit libaudiofile1 libaudit1 libaudit1-32bit libaugeas0 libauparse0 libavahi-client3 libavahi-client3-32bit libavahi-common3 libavahi-common3-32bit libavahi-glib1 libbasicobjects0 libblkid1 libblkid1-32bit libbluetooth3 libbluray1 libboost_program_options1_54_0 libboost_regex1_54_0 libboost_system1_54_0 libboost_thread1_54_0 libbrasero-burn3-1 libbrasero-media3-1 libbrasero-utils3-1 libbrlapi0_6 libbtrfs0 libburn4 libbz2-1 libbz2-1-32bit libcairo-gobject2 libcairo2 libcairo2-32bit libcairomm-1_0-1 libcamgm100 libcanberra-gtk3-0 libcanberra0 libcap-ng0 libcap2 libcap2-32bit libcares2 libcaribou0 libcdda_interface0 libcdda_paranoia0 libcdio14 libcdio_cdda1 libcdio_paranoia1 libcelt0-2 libcephfs1 libcheese-common libcheese-gtk23 libcheese7 libcloog-isl4 libclutter-1_0-0 libclutter-gst-2_0-0 libclutter-gtk-1_0-0 libcogl-pango15 libcogl15 libcollection2 libcolord-gtk1 libcolord2 libcom_err2 libcom_err2-32bit libcpupower0 libcrack2 libcrack2-32bit libcroco-0_6-3 libcroco-0_6-3-32bit libcryptmount0 libcryptmount0-32bit libcryptsetup4 libcryptsetup4-32bit libcurl4 libcurl4-32bit libdb-4_8 libdb-4_8-32bit libdbus-1-3 libdbus-1-3-32bit libdcerpc-binding0 libdcerpc-binding0-32bit libdcerpc0 libdcerpc0-32bit libdconf1 libdhash1 libdialog11 libdjvulibre21 libdm0 libdmx1 libdotconf0 libdrm2 libdrm2-32bit libdrm_intel1 libdrm_intel1-32bit libdrm_nouveau2 libdrm_nouveau2-32bit libdrm_radeon1 libdrm_radeon1-32bit libdv4 libdvdnav4 libdvdread4 libdw1 libedit0 libelf0 libelf1 libelf1-32bit libenca0 libenchant1 libesd0 libesmtp libestr0 libevdev2 libevdocument3-4 libevent-2_0-5 libevview3-3 libexempi3 libexif12 libexpat1 libexpat1-32bit libext2fs2 libfam0-gamin libffi4 libffi4-32bit libfftw3-3 libfipscheck1 libfipscheck1-32bit libfltk1 libfontenc1 libfreebl3 libfreebl3-32bit libfreetype6 libfreetype6-32bit libftgl2 libfuse2 libgbm1 libgbm1-32bit libgc1 libgcc_s1 libgcc_s1-32bit libgck-1-0 libgck-modules-gnome-keyring libgcr-3-1 libgcrypt20 libgcrypt20-32bit libgdbm4 libgdbm4-32bit libgdk_pixbuf-2_0-0 libgdm1 libgee-0_8-2 libgensec0 libgensec0-32bit libgeoclue0 libgeocode-glib0 libgif6-32bit libgio-2_0-0 libgio-2_0-0-32bit libgiomm-2_4-1 libgirepository-1_0-1 libgjs0 libglade-2_0-0 libglib-2_0-0 libglib-2_0-0-32bit libglibmm-2_4-1 libgme0 libgmime-2_6-0 libgmodule-2_0-0 libgmodule-2_0-0-32bit libgmp10 libgnome-bluetooth12 libgnome-desktop-3-8 libgnome-desktop-3_0-common libgnome-keyring-lang libgnome-keyring0 libgnome-menu-3-0 libgnomesu libgnomesu-lang libgnomesu0 libgnutls28 libgoa-1_0-0 libgoa-backend-1_0-1 libgobject-2_0-0 libgobject-2_0-0-32bit libgpg-error0 libgpg-error0-32bit libgpgme11 libgphoto2-6 libgphoto2-6-lang libgraphite2-3 libgraphite2-3-32bit libgsm1 libgssglue1 libgstallocators-1_0-0 libgstapp-1_0-0 libgstaudio-1_0-0 libgstbasecamerabinsrc-1_0-0 libgstcodecparsers-1_0-0 libgstegl-1_0-0 libgstfft-1_0-0 libgstmpegts-1_0-0 libgstpbutils-1_0-0 libgstphotography-1_0-0 libgstreamer-1_0-0 libgstriff-1_0-0 libgstrtp-1_0-0 libgstrtsp-1_0-0 libgstsdp-1_0-0 libgsttag-1_0-0 libgstvideo-1_0-0 libgthread-2_0-0 libgtk-2_0-0 libgtk-3-0 libgtkmm-3_0-1 libgtksourceview-3_0-1 libgtop-2_0-10 libgtop-lang libgucharmap_2_90-7 libgudev-1_0-0 libgvfscommon0 libgweather-3-6 libgweather-data libgweather-lang libgxps2 libharfbuzz-icu0 libharfbuzz0 libharfbuzz0-32bit libhavege1 libhogweed2 libibus-1_0-5 libical1 libicu52_1 libicu52_1-data libidn-tools libidn11 libidn11-32bit libimobiledevice4 libini_config3 libiptc0 libisl10 libisofs6 libiw30 libjack0 libjasper1 libjavascriptcoregtk-3_0-0 libjbig2 libjbig2-32bit libjpeg8 libjpeg8-32bit libjson-c2 libjson-glib-1_0-0 libkate1 libkeyutils1 libkeyutils1-32bit libkmod2 libkpathsea6 libksba8 liblcms1 liblcms1-32bit liblcms2-2 libldap-2_4-2 libldap-2_4-2-32bit libldapcpp1 libldb1 libldb1-32bit libleveldb1 liblockdev1 liblogging0 liblouis2 liblrdf2 libltdl7 liblua5_1 liblua5_1-32bit liblua5_2 liblzma5 liblzma5-32bit liblzo2-2 libmagic1 libmagic1-32bit libmjpegutils-2_0-0 libmm-glib0 libmms0 libmng1 libmng1-32bit libmnl0 libmodman1 libmodplug1 libmount1 libmount1-32bit libmozjs-17_0 libmpc3 libmpfr4 libmtdev1 libmtp9 libmutter0 libmysqlclient18 libnautilus-extension1 libncurses5 libncurses5-32bit libncurses6 libndr-krb5pac0 libndr-krb5pac0-32bit libndr-nbt0 libndr-nbt0-32bit libndr-standard0 libndr-standard0-32bit libndr0 libndr0-32bit libneon27 libnetapi0 libnetapi0-32bit libnetfilter_conntrack3 libnetpbm11 libnettle4 libnfnetlink0 libnl-config libnl1 libnl3-200 libnm-glib-vpn1 libnm-glib4 libnm-gtk0 libnm-util2 libnotify4 libnscd1 libnscd1-32bit libnsssharedhelper0 libnuma1 libofa0 libogg0 liboggkate1 libopenct1 libopenssl1_0_0 libopenssl1_0_0-32bit libopus0 liborc-0_4-0 libp11-kit0 libpackagekit-glib2-16 libpango-1_0-0 libpango-1_0-0-32bit libpangomm-1_4-1 libparted0 libpath_utils1 libpcap1 libpci3 libpci3-32bit libpciaccess0 libpciaccess0-32bit libpcre1 libpcre1-32bit libpcre16-0 libpdb0 libpdb0-32bit libpeas-1_0-0 libpeas-gtk-1_0-0 libpipeline1 libpixman-1-0 libpixman-1-0-32bit libplist1 libply-boot-client2 libply-splash-core2 libply-splash-graphics2 libply2 libpng16-16 libpng16-16-32bit libpolkit0 libpoppler-glib8 libpoppler44 libpopt0 libpopt0-32bit libportaudio2 libpq5 libprocps3 libproxy1 libproxy1-config-gnome3 libpth20 libpulse-mainloop-glib0 libpulse0 libpwquality-lang libpwquality1 libpyglib-gi-2_0-python2-0 libpyglib-gi-2_0-python3-0 libpython2_7-1_0 libpython2_7-1_0-32bit libpython3_4m1_0 libqpdf13 libqrencode3 libqt4 libqt4-32bit libqt4-sql libqt4-sql-32bit libqt4-sql-mysql libqt4-x11 libqt4-x11-32bit libquicktime0 libquvi libquvi-scripts librados2 libraptor2-0 librbd1 libreadline6 libref_array1 libregistry0 libreiserfscore0 librest0 librpcsecgss3 librsvg-2-2 libruby2_1-2_1 libsamba-credentials0 libsamba-credentials0-32bit libsamba-hostconfig0 libsamba-hostconfig0-32bit libsamba-util0 libsamba-util0-32bit libsamdb0 libsamdb0-32bit libsamplerate0 libsasl2-3 libsasl2-3-32bit libschroedinger-1_0-0 libseccomp2 libsecret-1-0 libsecret-lang libselinux1 libselinux1-32bit libsemanage1 libsemanage1-32bit libsensors4 libsepol1 libsepol1-32bit libsgutils2-2 libsigc-2_0-0 libslang2 libsmartcols1 libsmbclient-raw0 libsmbclient-raw0-32bit libsmbclient0 libsmbconf0 libsmbconf0-32bit libsmbldap0 libsmbldap0-32bit libsmi libsmi2 libsnapper2 libsnappy1 libsndfile1 libsnmp30 libsoftokn3 libsoftokn3-32bit libsolv-tools libsoup-2_4-1 libsoup-lang libspandsp2 libspectre1 libspeechd2 libspeex1 libspeexdsp1 libsqlite3-0 libsqlite3-0-32bit libssh2-1 libssh2-1-32bit libsss_idmap0 libstartup-notification-1-0 libstdc++6 libstdc++6-32bit libstorage-ruby libstorage5 libstroke libtag1 libtalloc2 libtalloc2-32bit libtasn1 libtasn1-6 libtdb1 libtdb1-32bit libtelepathy-glib0 libtelepathy-logger3 libtevent-util0 libtevent-util0-32bit libtevent0 libtevent0-32bit libtheora0 libtiff5 libtiff5-32bit libtirpc1 libtool libtool-32bit libtotem-plparser18 libtracker-common-0_16-0 libtracker-sparql-0_16-0 libttf2 libudev1 libudev1-32bit libudisks2-0 libunwind libunwind-devel libupower-glib3 libusb-0_1-4 libusb-1_0-0 libusbmuxd2 libustr-1_0-1 libustr-1_0-1-32bit libutempter0 libuuid1 libuuid1-32bit libv4l libv4l1-0 libv4l2-0 libv4lconvert0 libvdpau1 libvisual libvorbis0 libvorbisenc2 libvorbisfile3 libvpx1 libvte2_90-9 libwacom-data libwacom2 libwavpack1 libwbclient0 libwbclient0-32bit libwebkitgtk-3_0-0 libwebkitgtk3-lang libwebp5 libwebpmux1 libwebrtc_audio_processing0 libwicked-0-6 libwnck-3-0 libwnck-lang libwrap0 libwrap0-32bit libx86emu1 libxcb-dri2-0 libxcb-dri2-0-32bit libxcb-glx0 libxcb-glx0-32bit libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-render0 libxcb-render0-32bit libxcb-shape0 libxcb-shm0 libxcb-shm0-32bit libxcb-sync1 libxcb-util1 libxcb-xfixes0 libxcb-xfixes0-32bit libxcb-xkb1 libxcb-xv0 libxcb1 libxcb1-32bit libxkbcommon-x11-0 libxkbcommon0 libxkbfile1 libxklavier16 libxml2-2 libxml2-2-32bit libxml2-tools libxshmfence1 libxslt-tools libxslt1 libxtables10 libyaml-0-2 libyelp0 libyui-ncurses-pkg6 libyui-ncurses6 libyui-qt-pkg6 libyui-qt6 libyui6 libz1 libz1-32bit libzio1 libzmq3 libzypp listres lockdev logrotate lsb-release lsof lsscsi lua luasocket luit lvm2 m4 mailx make makedumpfile man man-pages man-pages-posix master-boot-code mc mc-lang mcelog mdadm metamail metatheme-adwaita-common mingetty mkfontdir mkfontscale mksh mlocate mozilla-nspr mozilla-nspr-32bit mozilla-nss mozilla-nss-32bit mozilla-nss-certs mozilla-nss-certs-32bit mpt-firmware mtools multipath-tools mutt mutter mutter-data mutter-lang nano nautilus nautilus-file-roller nautilus-lang nautilus-open-terminal nautilus-open-terminal-lang nautilus-share nautilus-share-lang ncurses-utils net-snmp net-tools netcat-openbsd netcfg netpbm nfs-client nfs-doc nfs-kernel-server nfsidmap notification-daemon notification-daemon-lang novell-sound-theme nscd ntp numactl ofl open-iscsi openct openldap2-client opensc openslp openslp-32bit openslp-server openssh openssh-askpass openssh-helpers openssl opie opie-32bit orca orca-lang os-prober p11-kit p11-kit-tools p7zip pam pam-32bit pam-config pam-doc pam-modules pam-modules-32bit pam_mount pam_mount-32bit pango-modules pango-modules-32bit parted patch patterns-sle-gnome-basic patterns-sles-32bit patterns-sles-Minimal patterns-sles-Minimal-32bit patterns-sles-apparmor patterns-sles-apparmor-32bit patterns-sles-base patterns-sles-base-32bit patterns-sles-documentation patterns-sles-documentation-32bit patterns-sles-x11 patterns-sles-x11-32bit pax pciutils pciutils-ids pcsc-lite perl perl-32bit perl-Bit-Vector perl-Bootloader perl-Bootloader-YAML perl-Carp-Clan perl-Config-Crontab perl-Config-IniFiles perl-Crypt-SmbHash perl-DBD-SQLite perl-DBI perl-Date-Calc perl-Digest-HMAC perl-Digest-MD4 perl-Digest-SHA1 perl-Encode-Locale perl-File-Listing perl-HTML-Parser perl-HTML-Tagset perl-HTTP-Cookies perl-HTTP-Daemon perl-HTTP-Date perl-HTTP-Message perl-HTTP-Negotiate perl-IO-HTML perl-IO-Socket-SSL perl-LWP-MediaTypes perl-LWP-Protocol-https perl-List-MoreUtils perl-Net-DBus perl-Net-DNS perl-Net-Daemon perl-Net-HTTP perl-Net-SSLeay perl-Parse-RecDescent perl-PlRPC perl-RPC-XML perl-SNMP perl-Sub-Uplevel perl-Term-ReadKey perl-Test-Exception perl-Tie-IxHash perl-TimeDate perl-URI perl-WWW-RobotRules perl-X11-Protocol perl-X500-DN perl-XML-LibXML perl-XML-NamespaceSupport perl-XML-Parser perl-XML-SAX perl-XML-SAX-Base perl-XML-SAX-Expat perl-XML-Simple perl-XML-Twig perl-XML-Writer perl-XML-XPath perl-XML-XPathEngine perl-YAML-LibYAML perl-apparmor perl-base perl-camgm perl-gettext perl-libwww-perl permissions pigz pinentry pkg-config plymouth plymouth-branding-SLE plymouth-dracut plymouth-plugin-label plymouth-plugin-script plymouth-scripts polkit polkit-default-privs polkit-gnome polkit-gnome-lang poppler-data poppler-tools postfix postgresql-init postgresql93 postgresql93-server ppp pptp prctl procinfo procmail procps psmisc psmisc-lang psutils pulseaudio pulseaudio-esound-compat pulseaudio-lang pulseaudio-module-x11 pulseaudio-utils pytalloc pytalloc-32bit python python-Django python-Flask python-Jinja2 python-M2Crypto python-Mako python-MarkupSafe python-Pillow python-PyYAML python-SQLAlchemy python-Twisted python-Werkzeug python-alembic python-apache-libcloud python-argparse python-base python-cairo python-carbon python-ceph python-cffi python-cryptography python-cups python-cupshelpers python-dateutil python-django-tagging python-djangorestframework python-ecdsa python-execnet python-gevent python-gobject python-gobject-cairo python-greenlet python-itsdangerous python-lxml python-msgpack-python python-pam python-paramiko python-psutil python-psycogreen python-psycopg2 python-pushy python-pyOpenSSL python-pycparser python-pycrypto python-pycurl python-pyparsing python-pyserial python-pytz python-pyzmq python-remoto python-requests python-setuptools python-simplejson python-six python-smbc python-solv python-whisper python-xml python-zerorpc python-zope.interface python3 python3-atspi python3-base python3-brlapi python3-cairo python3-gedit python3-gobject python3-louis python3-speechd quota readline-doc recode reiserfs release-notes-sles rendercheck rgb rpcbind rpm rpm-32bit rpm-python rsh rsync rsyslog rtkit ruby ruby-common ruby2.1 ruby2.1-rubygem-fast_gettext ruby2.1-rubygem-gem2rpm ruby2.1-rubygem-ruby-dbus ruby2.1-rubygem-suse-connect ruby2.1-stdlib salt salt-master salt-minion samba samba-32bit samba-client samba-client-32bit samba-libs samba-libs-32bit scout screen sed sed-lang sessreg setxkbmap sg3_utils sgml-skel shadow shared-mime-info sharutils sharutils-lang sles-admin_en-pdf sles-deployment_en-pdf sles-installquick_en-pdf sles-manuals_en sles-release sles-security_en-pdf sles-storage_en-pdf sles-tuning_en-pdf smartmontools snapper snapper-zypp-plugin snmp-mibs sound-theme-freedesktop speech-dispatcher speech-dispatcher-module-espeak sqlite3 sssd sssd-32bit sssd-krb5-common sssd-ldap star strace strace-32bit sudo supportutils suse-build-key suse-module-tools susehelp susehelp_en sysconfig sysconfig-netconfig sysfsutils sysfsutils-32bit syslinux syslog-service system-config-printer-common system-config-printer-common-lang system-config-printer-dbus-service systemd systemd-32bit systemd-bash-completion systemd-presets-branding-SLE systemd-sysvinit sysvinit-tools tar tar-lang tcl tcl-32bit tcpd tcpdump tcsh telnet terminfo terminfo-base tigervnc time timezone tk tk-32bit totem-pl-parser totem-pl-parser-lang traceroute typelib-1_0-AccountsService-1_0 typelib-1_0-Atk-1_0 typelib-1_0-Atspi-2_0 typelib-1_0-Caribou-1_0 typelib-1_0-Clutter-1_0 typelib-1_0-Cogl-1_0 typelib-1_0-CoglPango-1_0 typelib-1_0-GMenu-3_0 typelib-1_0-Gck-1 typelib-1_0-Gcr-3 typelib-1_0-GdkPixbuf-2_0 typelib-1_0-Gdm-1_0 typelib-1_0-GjsPrivate-1_0 typelib-1_0-GnomeBluetooth-1_0 typelib-1_0-GnomeDesktop-3_0 typelib-1_0-GnomeKeyring-1_0 typelib-1_0-Gtk-3_0 typelib-1_0-GtkSource-3_0 typelib-1_0-IBus-1_0 typelib-1_0-Json-1_0 typelib-1_0-Meta-3_0 typelib-1_0-NMClient-1_0 typelib-1_0-NMGtk-1_0 typelib-1_0-NetworkManager-1_0 typelib-1_0-Notify-0_7 typelib-1_0-PackageKitGlib-1_0 typelib-1_0-Pango-1_0 typelib-1_0-Peas-1_0 typelib-1_0-PeasGtk-1_0 typelib-1_0-Polkit-1_0 typelib-1_0-Soup-2_4 typelib-1_0-TelepathyGlib-0_12 typelib-1_0-TelepathyLogger-0_2 typelib-1_0-UpowerGlib-1_0 typelib-1_0-Wnck-3_0 ucode-intel udev udev-configure-printer udisks2 udisks2-lang unclutter unrar unzip update-alternatives upower upower-lang usbmuxd usbutils util-linux util-linux-lang util-linux-systemd viewres vim vim-data vino vino-lang vlan vlock vorbis-tools vorbis-tools-lang vsftpd vte-lang w3m wallpaper-branding-SLE wget which wicked wicked-service wireless-tools wodim x11-tools x11perf x86info xauth xbacklight xbitmaps xclock xconsole xcursor-themes xcursorgen xdg-menu xdg-user-dirs xdg-user-dirs-gtk xdg-user-dirs-gtk-lang xdg-user-dirs-lang xdg-utils xdm xdmbgrd xdpyinfo xev xeyes xf86-input-evdev xf86-input-synaptics xf86-input-vmmouse xf86-input-void xf86-input-wacom xf86-video-fbdev xf86-video-mga xf86-video-modesetting xf86-video-vesa xfd xfontsel xfsprogs xgamma xhost xinetd xinit xinput xkbcomp xkbevd xkbprint xkbutils xkeyboard-config xkeyboard-config-lang xkill xlockmore xlogo xlsatoms xlsclients xlsfonts xmag xmessage xmodmap xorg-x11 xorg-x11-Xvnc xorg-x11-driver-video xorg-x11-essentials xorg-x11-fonts xorg-x11-fonts-core xorg-x11-libs xorg-x11-server xorg-x11-server-extra xprop xrandr xrdb xrestop xscope xscreensaver xscreensaver-data xset xsetmode xsetpointer xsetroot xtables-plugins xterm xtermset xvinfo xwd xwininfo xz xz-lang yast2 yast2-add-on yast2-apparmor yast2-audit-laf yast2-auth-client yast2-auth-server yast2-boot-server yast2-bootloader yast2-branding-SLE yast2-ca-management yast2-control-center yast2-control-center-gnome yast2-core yast2-country yast2-country-data yast2-dhcp-server yast2-dns-server yast2-firewall yast2-ftp-server yast2-hardware-detection yast2-http-server yast2-inetd yast2-installation yast2-instserver yast2-iscsi-client yast2-isns yast2-kdump yast2-ldap yast2-mail yast2-metapackage-handler yast2-network yast2-nfs-client yast2-nfs-common yast2-nfs-server yast2-nis-client yast2-nis-server yast2-ntp-client yast2-online-update yast2-online-update-frontend yast2-packager yast2-pam yast2-perl-bindings yast2-pkg-bindings yast2-printer yast2-proxy yast2-registration yast2-ruby-bindings yast2-samba-client yast2-samba-server yast2-schema yast2-security yast2-services-manager yast2-slp yast2-snapper yast2-sound yast2-squid yast2-storage yast2-sudo yast2-support yast2-sysconfig yast2-tftp-server yast2-theme-SLE yast2-trans-en_US yast2-trans-stats yast2-transfer yast2-update yast2-users yast2-vm yast2-x11 yast2-xml yast2-ycp-ui-bindings yelp yelp-lang yelp-xsl yp-tools ypbind zenity zenity-lang zip zisofs-tools zsh zypp-plugin-python zypper zypper-log zypper
ory 'ceph_disk1' is out-of-date. You can run 'zypper refresh' as root to update it.
Specified path '/home/col/down' is not a directory: dir:///home/col/down

Abort, retry, ignore? [a/r/i/? shows all options] (a): a
Repository 'ceph_disk2' is out-of-date. You can run 'zypper refresh' as root to update it.
Loading repository data...
Repository 'SLES12-12-0' not cached. Caching...
Building repository 'SLES12-12-0' cache ..................................[done]
Retrieving repository 'ceph_disk1' data...
Retrieving repository 'ceph_disk1' metadata ---------------------------------[|]
Specified path '/home/col/down' is not a directory: dir:///home/col/down

Abort, retry, ignore? [a/r/i/? shows all options] (a): a
Retrieving repository 'ceph_disk1' metadata .............................[error]
Repository 'ceph_disk1' is invalid.
[ceph_disk1|iso:///?iso=/home/col/down/SUSE-Enterprise-Storage-1.0-DVD-x86_64-Build0131-Media1.iso] Valid metadata not found at specified URL
Please check if the URIs defined for this repository are pointing to a valid repository.
Problem loading data from 'ceph_disk1'
Resolvables from 'ceph_disk1' not loaded because of error.
Retrieving repository 'ceph_disk2' data...
Retrieving repository 'ceph_disk2' metadata ---------------------------------[/]
Specified path '/home/col/down' is not a directory: dir:///home/col/down

Abort, retry, ignore? [a/r/i/? shows all options] (a): a
**Retrieving repository 'ceph_disk2' metadata .............................[error]**
Repository 'ceph_disk2' is invalid.
[ceph_disk2|iso:///?iso=/home/col/down/SUSE-Enterprise-Storage-1.0-DVD-x86_64-Build0131-Media2.iso] Valid metadata not found at specified URL
Please check if the URIs defined for this repository are pointing to a valid repository.
Problem loading data from 'ceph_disk2'
Resolvables from 'ceph_disk2' not loaded because of error.
Reading installed packages...
Package 'apache2-mod_wsgi' not found.
Package 'python-Django' not found.
Package 'python-Flask' not found.
Package 'python-Jinja2' not found.
Package 'python-Mako' not found.
Package 'python-MarkupSafe' not found.
Package 'python-Pillow' not found.
Package 'python-PyYAML' not found.
Package 'python-SQLAlchemy' not found.
Package 'python-Twisted' not found.
Package 'python-Werkzeug' not found.
Package 'python-alembic' not found.
Package 'python-apache-libcloud' not found.
Package 'python-carbon' not found.
Package 'python-dateutil' not found.
Package 'python-django-tagging' not found.
Package 'python-djangorestframework' not found.
Package 'python-ecdsa' not found.
Package 'python-execnet' not found.
Package 'python-gevent' not found.
Package 'python-greenlet' not found.
Package 'python-itsdangerous' not found.
Package 'python-msgpack-python' not found.
Package 'python-paramiko' not found.
Package 'python-psutil' not found.
Package 'python-psycogreen' not found.
Package 'python-psycopg2' not found.
Package 'python-pushy' not found.
Package 'python-pycrypto' not found.
Package 'python-pyserial' not found.
Package 'python-pytz' not found.
Package 'python-pyzmq' not found.
Package 'python-remoto' not found.
Package 'python-setuptools' not found.
Package 'python-whisper' not found.
Package 'python-zerorpc' not found.
Package 'python-zope.interface' not found.
'ceph' not found in package names. Trying capabilities.
No provider of 'ceph' found.
'calamari-clients' not found in package names. Trying capabilities.
No provider of 'calamari-clients' found.
'calamari-server' not found in package names. Trying capabilities.
No provider of 'calamari-server' found.
'ceph-deploy' not found in package names. Trying capabilities.
No provider of 'ceph-deploy' found.
'graphite-web' not found in package names. Trying capabilities.
No provider of 'graphite-web' found.
'libleveldb1' not found in package names. Trying capabilities.
No provider of 'libleveldb1' found.
'libwebpmux1' not found in package names. Trying capabilities.
No provider of 'libwebpmux1' found.
'libzmq3' not found in package names. Trying capabilities.
No provider of 'libzmq3' found.
'nano' not found in package names. Trying capabilities.
No provider of 'nano' found.
'salt' not found in package names. Trying capabilities.
No provider of 'salt' found.
'salt-master' not found in package names. Trying capabilities.
No provider of 'salt-master' found.
'salt-minion' not found in package names. Trying capabilities.
No provider of 'salt-minion' found.
Jun-24 15:18:17 <1> : EXEC [rm -f /tmp/machinery-image20150624-5413-k2qelu/build/image-root/screenrc.smart*]
Jun-24 15:18:17 <1> : EXEC [rm -f /tmp/machinery-image20150624-5413-k2qelu/build/image-root/screenrc.ctrls]
Jun-24 15:18:17 <1> : EXEC [rm -f /tmp/machinery-image20150624-5413-k2qelu/build/image-root/screenrc.err]
Jun-24 15:18:17 <1> : EXEC [test -d "/tmp/machinery-image20150624-5413-k2qelu/build/image-root/proc"]
Jun-24 15:18:17 <1> : Umounting path: /tmp/machinery-image20150624-5413-k2qelu/build/image-root/proc
Jun-24 15:18:17 <1> : EXEC [umount "/tmp/machinery-image20150624-5413-k2qelu/build/image-root/proc" 2>&1]
Jun-24 15:18:17 <1> : EXEC [test -d "/tmp/machinery-image20150624-5413-k2qelu/build/image-root//var/cache/kiwi"]
Jun-24 15:18:17 <1> : Umounting path: /tmp/machinery-image20150624-5413-k2qelu/build/image-root//var/cache/kiwi
Jun-24 15:18:17 <1> : EXEC [umount "/tmp/machinery-image20150624-5413-k2qelu/build/image-root//var/cache/kiwi" 2>&1]
Jun-24 15:18:17 <1> : EXEC [test -d "/tmp/machinery-image20150624-5413-k2qelu/build/image-root/dev"]
Jun-24 15:18:17 <1> : Umounting path: /tmp/machinery-image20150624-5413-k2qelu/build/image-root/dev
Jun-24 15:18:17 <1> : EXEC [umount "/tmp/machinery-image20150624-5413-k2qelu/build/image-root/dev" 2>&1]
Jun-24 15:18:17 <1> : Release package manager lock
Jun-24 15:18:17 <1> : EXEC [rm -f /var/lock/kiwi-init.lock]

Jun-24 15:18:17 <3> : KIWI exited with error(s)
Jun-24 15:18:17 <1> : Release package manager lock
Jun-24 15:18:17 <1> : EXEC [rm -f /var/lock/kiwi-init.lock]
Jun-24 15:18:17 <1> : Release package manager lock
Jun-24 15:18:17 <1> : EXEC [rm -f /var/lock/kiwi-init.lock]
Jun-24 15:18:17 <1> : EXEC [rm -f /var/cache/kiwi/zypper/zypper.conf.5428/var/cache/kiwi/zypper/zypp.conf.5428]



```

### PR DESCRIPTION
**Pull request by vwallfahrer**
Fixes #1032

### CODE REVIEW

File: lib/build_task.rb [hunk 1]
```diff
@@ -22,6 +22,11 @@ def build(system_description, output_path, options = {})
     LocalSystem.validate_existence_of_package("kiwi")
     LocalSystem.validate_existence_of_package("kiwi-desc-vmxboot")
 
+    if !system_description["repositories"].any? { |repo| repo.enabled && !repo.external_medium? }
```
Comment (thardeck) [inline lib/build_task.rb]: This is already tested in kiwi_config

**Comment by thardeck** [comment]
lgtm
