### PR TITLE
Fix 2041

### LINKED ISSUE #2041: /machinery-tool-1.18.0/lib/array.rb:187:in `[]': no implicit conversion of String into Integer (TypeError) after format upgrade from 5 to 7
Trying to re-run machinery with a previsously inspected machine ask me to upgrade the format.
(Machine is 13.1) As this happened the second time I report the trace.

```
machinery show yoda
yoda: format version 5, needs to be upgraded. Try 'machinery upgrade-format yoda' to upgrade it to the current version.
bruno@qt-kt:~$ machinery upgrade-format yoda
Reading 'yoda' ... Successfully upgraded from version 5 to 7.
bruno@qt-kt:~$ machinery show yoda
bruno@qt-kt:~$ machinery inspect yoda
Inspecting yoda for os, packages, patterns, repositories, users, groups, services, config-files, changed-managed-files, unmanaged-files...

Note: There are filters being applied during inspection. (Use `--verbose` option to show the filters)


Inspecting os...
Machinery experienced an unexpected error. Please file a bug report at: https://github.com/SUSE/machinery/issues/new
/usr/lib64/ruby/gems/2.2.0/gems/machinery-tool-1.18.0/lib/array.rb:187:in `[]': no implicit conversion of String into Integer (TypeError)
        from /usr/lib64/ruby/gems/2.2.0/gems/machinery-tool-1.18.0/lib/array.rb:187:in `method_missing'
        from /usr/lib64/ruby/gems/2.2.0/gems/machinery-tool-1.18.0/lib/filter.rb:151:in `block (2 levels) in apply!'
        from /usr/lib64/ruby/gems/2.2.0/gems/machinery-tool-1.18.0/lib/filter.rb:149:in `each'
        from /usr/lib64/ruby/gems/2.2.0/gems/machinery-tool-1.18.0/lib/filter.rb:149:in `block in apply!'
        from /usr/lib64/ruby/gems/2.2.0/gems/machinery-tool-1.18.0/lib/filter.rb:143:in `each'
        from /usr/lib64/ruby/gems/2.2.0/gems/machinery-tool-1.18.0/lib/filter.rb:143:in `apply!'
        from /usr/lib64/ruby/gems/2.2.0/gems/machinery-tool-1.18.0/lib/inspect_task.rb:96:in `block in build_description'
        from /usr/lib64/ruby/gems/2.2.0/gems/machinery-tool-1.18.0/lib/inspect_task.rb:79:in `each'
        from /usr/lib64/ruby/gems/2.2.0/gems/machinery-tool-1.18.0/lib/inspect_task.rb:79:in `build_description'
        from /usr/lib64/ruby/gems/2.2.0/gems/machinery-tool-1.18.0/lib/inspect_task.rb:21:in `inspect_system'
        from /usr/lib64/ruby/gems/2.2.0/gems/machinery-tool-1.18.0/lib/cli.rb:610:in `block (2 levels) in <class:Cli>'
        from /usr/lib64/ruby/gems/2.2.0/gems/gli-2.13.1/lib/gli/command_support.rb:126:in `call'
        from /usr/lib64/ruby/gems/2.2.0/gems/gli-2.13.1/lib/gli/command_support.rb:126:in `execute'
        from /usr/lib64/ruby/gems/2.2.0/gems/gli-2.13.1/lib/gli/app_support.rb:296:in `block in call_command'
        from /usr/lib64/ruby/gems/2.2.0/gems/gli-2.13.1/lib/gli/app_support.rb:309:in `call'
        from /usr/lib64/ruby/gems/2.2.0/gems/gli-2.13.1/lib/gli/app_support.rb:309:in `call_command'
        from /usr/lib64/ruby/gems/2.2.0/gems/gli-2.13.1/lib/gli/app_support.rb:83:in `run'
        from /usr/lib64/ruby/gems/2.2.0/gems/machinery-tool-1.18.0/bin/machinery:33:in `<top (required)>'
        from /usr/bin/machinery:23:in `load'
        from /usr/bin/machinery:23:in `<main>'

```
What kind of other information could help you?

### PR DESCRIPTION
**Pull request by thardeck**
Fixes #2041

### CODE REVIEW

File: schema/migrations/migrate8to9.rb [hunk 1]
```diff
@@ -0,0 +1,35 @@
+# Copyright (c) 2013-2014 SUSE LLC
```
Comment (mauromorales) [inline schema/migrations/migrate8to9.rb]: Minor detail but these should be 2016

**Comment by mauromorales** [comment]
lgtm
